import {describe,expect,it} from 'vitest';
import {buildChord,buildFretboard,buildVoicings,getChordFromScale,getParentMajor,getPitchClass,getScaleByKey,getScaleNotes} from '../theory';
describe('escalas y spelling',()=>{const cases:[string,Parameters<typeof getScaleNotes>[1],string[]][]=[['C','major',['C','D','E','F','G','A','B']],['G','major',['G','A','B','C','D','E','F#']],['F','major',['F','G','A','Bb','C','D','E']],['Bb','major',['Bb','C','D','Eb','F','G','A']],['D','major',['D','E','F#','G','A','B','C#']],['Eb','major',['Eb','F','G','Ab','Bb','C','D']],['F#','major',['F#','G#','A#','B','C#','D#','E#']],['G','mixolydian',['G','A','B','C','D','E','F']],['D','dorian',['D','E','F','G','A','B','C']],['E','phrygian',['E','F','G','A','B','C','D']],['F','lydian',['F','G','A','B','C','D','E']],['A','aeolian',['A','B','C','D','E','F','G']],['B','locrian',['B','C','D','E','F','G','A']],['C','major-pentatonic',['C','D','E','G','A']],['A','minor-pentatonic',['A','C','D','E','G']],['A','minor-blues',['A','C','D','Eb','E','G']]];it.each(cases)('%s %s',(root,key,notes)=>expect(getScaleNotes(root,key)).toEqual(notes));it('no inventa característica para pentatónica mayor',()=>expect(getScaleByKey('major-pentatonic').characteristicDegree).toBeUndefined())});
describe('acordes',()=>{const cases:[string,Parameters<typeof buildChord>[1],string[]][]=[['C','major',['C','E','G']],['C','minor',['C','Eb','G']],['B','diminished',['B','D','F']],['F#','major',['F#','A#','C#']],['Bb','major',['Bb','D','F']],['C#','diminished',['C#','E','G']],['C','dominant7',['C','E','G','Bb']],['B','major7',['B','D#','F#','A#']],['F#','halfDiminished7',['F#','A','C','E']],['B','diminished7',['B','D','F','Ab']]];it.each(cases)('%s %s',(root,type,notes)=>expect(buildChord(root,type)?.notes).toEqual(notes))});
describe('armonización',()=>{const cases:[string,Parameters<typeof getChordFromScale>[1],string[],string[]][]=[['C','major',['C','Dm','Em','F','G','Am','Bdim'],['I','ii','iii','IV','V','vi','vii°']],['G','mixolydian',['G','Am','Bdim','C','Dm','Em','F'],['I','ii','iii°','IV','v','vi','bVII']],['D','dorian',['Dm','Em','F','G','Am','Bdim','C'],['i','ii','bIII','IV','v','vi°','bVII']],['A','aeolian',['Am','Bdim','C','Dm','Em','F','G'],['i','ii°','bIII','iv','v','bVI','bVII']]];it.each(cases)('%s %s',(root,key,labels,romans)=>{const h=getChordFromScale(root,key);expect(h.map(c=>c.label)).toEqual(labels);expect(h.map(c=>c.degreeName)).toEqual(romans)})});
describe('escala mayor madre',()=>{it.each([['G','mixolydian','C'],['D','dorian','C'],['E','phrygian','C'],['F','lydian','C'],['A','aeolian','C'],['B','locrian','C']] as const)('%s %s',(root,key,parent)=>expect(getParentMajor(root,key)?.root).toBe(parent));it('funciona con alteraciones',()=>expect(getParentMajor('Bb','mixolydian')?.root).toBe('Eb'))});
describe('mástil',()=>{it('devuelve 6 cuerdas y 23 posiciones con datos separados',()=>{const board=buildFretboard('G','mixolydian');expect(board).toHaveLength(6);expect(board.every(row=>row.length===23)).toBe(true);expect(board[0][3]).toMatchObject({pitchClass:7,noteName:'G',fret:3,string:'E',inScale:true,degree:'1',isRoot:true,isCharacteristic:false})});it('marca el rasgo sólo cuando existe',()=>{expect(buildFretboard('C','major-pentatonic').flat().some(cell=>cell.isCharacteristic)).toBe(false);expect(buildFretboard('G','mixolydian').flat().some(cell=>cell.degree==='b7'&&cell.isCharacteristic)).toBe(true)})});
describe('nuevas escalas menores',()=>{it('A menor armónica',()=>expect(getScaleNotes('A','harmonic-minor')).toEqual(['A','B','C','D','E','F','G#']));it('A menor melódica',()=>expect(getScaleNotes('A','melodic-minor')).toEqual(['A','B','C','D','E','F#','G#']))});
describe('voicings',()=>{it('genera posiciones completas y tocables para C mayor',()=>{const voicings=buildVoicings('C','major');expect(voicings.length).toBeGreaterThan(0);for(const voicing of voicings){const pitches=new Set(voicing.positions.map(p=>p.pitchClass));expect([0,4,7].every(p=>pitches.has(getPitchClass(['C','E','G'][[0,4,7].indexOf(p)])!))).toBe(true);expect(voicing.maxFret-voicing.minFret).toBeLessThanOrEqual(4)}});it('clasifica inversiones según la nota del bajo',()=>{const voicings=buildVoicings('C','major');expect(new Set(voicings.map(v=>v.inversion))).toContain('root');expect(voicings.every(v=>v.positions[0].noteName===v.bassNote)).toBe(true)})});
