import {buildChord,type ChordQuality,type ChordRecord} from './chords';
import {cycleLetter,getPitchClass,spellPitchWithLetter} from './notes';

export type MusicalStyle='Pop'|'Rock'|'Blues'|'Jazz'|'Soul / R&B'|'Funk'|'Bossa nova'|'Tango'|'Folklore argentino'|'Reggae'|'Flamenco'|'Metal'|'Cine';
export type ProgressionMode='major'|'minor'|'either';
export type StyleProgressionStep={degree:number;semitones:number;quality:ChordQuality;roman:string};
export type StyleProgression={id:string;name:string;style:MusicalStyle;mode:ProgressionMode;description:string;meter:string;difficulty:'Inicial'|'Intermedia'|'Avanzada';steps:readonly StyleProgressionStep[]};
export type ResolvedStyleProgression={preset:StyleProgression;chords:ChordRecord[]};

export const STYLE_PROGRESSIONS:readonly StyleProgression[]=[
 {id:'pop-axis',name:'Axis pop',style:'Pop',mode:'major',description:'Ciclo estable y muy reutilizable.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'major',roman:'I'},{degree:5,semitones:7,quality:'major',roman:'V'},{degree:6,semitones:9,quality:'minor',roman:'vi'},{degree:4,semitones:5,quality:'major',roman:'IV'}]},
 {id:'pop-minor',name:'Pop melancólico',style:'Pop',mode:'minor',description:'La relativa menor ocupa el centro perceptivo.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'minor',roman:'i'},{degree:6,semitones:8,quality:'major',roman:'bVI'},{degree:3,semitones:3,quality:'major',roman:'bIII'},{degree:7,semitones:10,quality:'major',roman:'bVII'}]},
 {id:'rock-bVII',name:'Rock mixolidio',style:'Rock',mode:'major',description:'Color modal por el acorde bVII.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'major',roman:'I'},{degree:7,semitones:10,quality:'major',roman:'bVII'},{degree:4,semitones:5,quality:'major',roman:'IV'},{degree:1,semitones:0,quality:'major',roman:'I'}]},
 {id:'blues-basic',name:'Blues de 12 compases — base',style:'Blues',mode:'major',description:'Funciones I7, IV7 y V7; el ritmo define el lenguaje.',meter:'4/4 shuffle',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'dominant7',roman:'I7'},{degree:4,semitones:5,quality:'dominant7',roman:'IV7'},{degree:1,semitones:0,quality:'dominant7',roman:'I7'},{degree:5,semitones:7,quality:'dominant7',roman:'V7'}]},
 {id:'jazz-251',name:'ii–V–I',style:'Jazz',mode:'major',description:'Cadencia central del lenguaje tonal de jazz.',meter:'4/4',difficulty:'Intermedia',steps:[{degree:2,semitones:2,quality:'minor7',roman:'ii7'},{degree:5,semitones:7,quality:'dominant7',roman:'V7'},{degree:1,semitones:0,quality:'major7',roman:'Imaj7'}]},
 {id:'jazz-turnaround',name:'Turnaround',style:'Jazz',mode:'major',description:'I–vi–ii–V para volver al comienzo.',meter:'4/4',difficulty:'Intermedia',steps:[{degree:1,semitones:0,quality:'major7',roman:'Imaj7'},{degree:6,semitones:9,quality:'minor7',roman:'vi7'},{degree:2,semitones:2,quality:'minor7',roman:'ii7'},{degree:5,semitones:7,quality:'dominant7',roman:'V7'}]},
 {id:'soul-minor-four',name:'Subdominante menor',style:'Soul / R&B',mode:'major',description:'El iv prestado aporta una resolución nostálgica.',meter:'4/4',difficulty:'Intermedia',steps:[{degree:1,semitones:0,quality:'major7',roman:'Imaj7'},{degree:3,semitones:4,quality:'minor7',roman:'iii7'},{degree:4,semitones:5,quality:'major7',roman:'IVmaj7'},{degree:4,semitones:5,quality:'minor',roman:'iv'}]},
 {id:'funk-dorian',name:'Vamp dórico',style:'Funk',mode:'minor',description:'Dos acordes para sostener un groove modal.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'minor7',roman:'i7'},{degree:4,semitones:5,quality:'dominant7',roman:'IV7'}]},
 {id:'bossa-2516',name:'Bossa ii–V–I–VI',style:'Bossa nova',mode:'major',description:'Turnaround con dominante secundaria al final.',meter:'4/4',difficulty:'Avanzada',steps:[{degree:2,semitones:2,quality:'minor7',roman:'ii7'},{degree:5,semitones:7,quality:'dominant7',roman:'V7'},{degree:1,semitones:0,quality:'major7',roman:'Imaj7'},{degree:6,semitones:9,quality:'dominant7',roman:'VI7'}]},
 {id:'tango-minor',name:'Cadencia menor tanguera',style:'Tango',mode:'minor',description:'Movimiento funcional i–iv–V7–i.',meter:'2/4 o 4/4',difficulty:'Intermedia',steps:[{degree:1,semitones:0,quality:'minor',roman:'i'},{degree:4,semitones:5,quality:'minor',roman:'iv'},{degree:5,semitones:7,quality:'dominant7',roman:'V7'},{degree:1,semitones:0,quality:'minor',roman:'i'}]},
 {id:'folklore-basic',name:'Giro folklórico',style:'Folklore argentino',mode:'major',description:'Base funcional adaptable a zamba o chacarera según el ritmo.',meter:'6/8 o 3/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'major',roman:'I'},{degree:4,semitones:5,quality:'major',roman:'IV'},{degree:5,semitones:7,quality:'major',roman:'V'},{degree:1,semitones:0,quality:'major',roman:'I'}]},
 {id:'reggae-basic',name:'One-drop armónico',style:'Reggae',mode:'major',description:'Ciclo popular; el contratiempo define el estilo.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'major',roman:'I'},{degree:5,semitones:7,quality:'major',roman:'V'},{degree:6,semitones:9,quality:'minor',roman:'vi'},{degree:4,semitones:5,quality:'major',roman:'IV'}]},
 {id:'andalusian',name:'Cadencia andaluza',style:'Flamenco',mode:'minor',description:'Descenso i–bVII–bVI–V.',meter:'Variable',difficulty:'Intermedia',steps:[{degree:1,semitones:0,quality:'minor',roman:'i'},{degree:7,semitones:10,quality:'major',roman:'bVII'},{degree:6,semitones:8,quality:'major',roman:'bVI'},{degree:5,semitones:7,quality:'major',roman:'V'}]},
 {id:'metal-minor',name:'Descenso épico',style:'Metal',mode:'minor',description:'Movimiento i–bVI–bVII de gran peso modal.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'minor',roman:'i'},{degree:6,semitones:8,quality:'major',roman:'bVI'},{degree:7,semitones:10,quality:'major',roman:'bVII'},{degree:1,semitones:0,quality:'minor',roman:'i'}]},
 {id:'cinematic',name:'Épico menor',style:'Cine',mode:'minor',description:'Ciclo amplio frecuente en música narrativa.',meter:'4/4',difficulty:'Inicial',steps:[{degree:1,semitones:0,quality:'minor',roman:'i'},{degree:6,semitones:8,quality:'major',roman:'bVI'},{degree:3,semitones:3,quality:'major',roman:'bIII'},{degree:7,semitones:10,quality:'major',roman:'bVII'}]},
];

export const MUSICAL_STYLES=[...new Set(STYLE_PROGRESSIONS.map(preset=>preset.style))];
export function resolveStyleProgression(root:string,preset:StyleProgression):ResolvedStyleProgression|null{const rootPitch=getPitchClass(root);if(rootPitch===null)return null;const chords=preset.steps.map(step=>{const letter=cycleLetter(root[0],step.degree-1);const chordRoot=spellPitchWithLetter(rootPitch+step.semitones,letter);const chord=buildChord(chordRoot,step.quality)!;return{...chord,degreeName:step.roman}});return{preset,chords}}
