import type {Difficulty,LickSection,LickStyle,ReferenceLick,Technique,VerifiedTheory} from './types';import type {ScaleKey} from '../music/scales';import {VERIFIED_REFERENCE_LICKS} from './documented';
type Seed=[id:string,artist:string,song:string,album:string|undefined,style:LickStyle,section:LickSection,key:string,scales:ScaleKey[],concepts:string[],techniques:Technique[],difficulty:Difficulty,families:string[],influences?:string[]];
const seeds:Seed[]=[
['mayer-gravity-opening','John Mayer','Gravity','Continuum','soul','opening-fills','G',['major-pentatonic','minor-pentatonic'],['space','chord-tone targeting','minor/major blues mixture'],['slide','bend'],2,['minor/major blues mixture','targeting the 3rd','space / phrasing'],['B.B. King','Jimi Hendrix']],
['mayer-slow-dancing-intro','John Mayer','Slow Dancing in a Burning Room','Continuum','pop-blues','intro','C#',['minor-pentatonic','dorian'],['melodic bends','space','chord-tone targeting'],['bend','vibrato'],3,['legato pentatonic','targeting the 3rd','space / phrasing'],['B.B. King','Stevie Ray Vaughan']],
['mayer-who-did-you-think','John Mayer','Who Did You Think I Was','Try!','blues-rock','live-improvisation','E',['minor-pentatonic','minor-blues'],['lead vocabulary','rhythmic phrasing'],['bend','hammer-on'],4,['minor/major blues mixture','double-stop pentatonic'],['Stevie Ray Vaughan','Jimi Hendrix']],
['mayer-out-of-my-mind','John Mayer','Out of My Mind','Where the Light Is','blues','solo','D',['minor-pentatonic','minor-blues','major-pentatonic'],['slow blues phrasing','call and response'],['bend','vibrato'],4,['BB Box','b3 → 3','space / phrasing'],['B.B. King']],
['mayer-belief-fills','John Mayer','Belief','Continuum','pop-blues','verse-fill','D',['minor-pentatonic','major-pentatonic'],['fills between chords','rhythmic space'],['slide','double-stop'],3,['double-stop pentatonic','targeting the 3rd'],['Jimi Hendrix']],
['bb-thrill-opening','B.B. King','The Thrill Is Gone','Completely Well','blues','opening-fills','B',['minor-pentatonic','minor-blues'],['call and response','expressive phrasing'],['bend','vibrato'],3,['BB Box','bend resolution','vibrato']],
['bb-three-oclock','B.B. King',"Three O'Clock Blues",undefined,'blues','opening-fills','C',['minor-pentatonic','major-pentatonic'],['slow blues phrasing','space'],['bend','vibrato'],3,['BB Box','major/minor blues mixture','space / phrasing']],
['bb-how-blue','B.B. King','How Blue Can You Get',undefined,'blues','verse-fill','C',['minor-pentatonic','major-pentatonic'],['call and response','vocal phrasing'],['bend','vibrato'],3,['call and response','targeting the 3rd','BB Box']],
['bb-every-day','B.B. King','Every Day I Have the Blues',undefined,'blues','solo','Bb',['minor-pentatonic','major-pentatonic'],['dominant blues vocabulary','resolution'],['bend','slide'],3,['targeting the 7th','bend resolution','BB Box']],
['bb-lucille','B.B. King','Lucille','Lucille','blues','solo','E',['minor-pentatonic','major-pentatonic'],['slow blues phrasing','narrative phrasing'],['bend','vibrato'],3,['BB Box','vibrato','call and response']],
['srv-texas-flood','Stevie Ray Vaughan','Texas Flood','Texas Flood','blues-rock','opening-fills','Eb',['minor-pentatonic','minor-blues','major-pentatonic'],['slow blues','dynamic phrasing'],['bend','vibrato'],5,['Texas blues','Albert King bend','major/minor blues mixture'],['Albert King','B.B. King']],
['srv-pride-and-joy','Stevie Ray Vaughan','Pride and Joy','Texas Flood','blues-rock','verse-fill','Eb',['minor-pentatonic','major-pentatonic'],['shuffle articulation','rhythm and lead'],['slide','hammer-on'],4,['shuffle lead/rhythm','double-stop pentatonic','Texas blues'],['Jimi Hendrix']],
['srv-lenny','Stevie Ray Vaughan','Lenny','Texas Flood','soul','verse-fill','E',['major-pentatonic','lydian'],['chord melody','space'],['chord-embellishment','slide'],4,['Hendrix chord embellishment','double-stop pentatonic'],['Jimi Hendrix']],
['srv-mary-lamb','Stevie Ray Vaughan','Mary Had a Little Lamb','Texas Flood','blues-rock','verse-fill','E',['minor-pentatonic','major-pentatonic'],['blues fills','shuffle phrasing'],['double-stop','bend'],4,['Texas blues','minor pentatonic','shuffle lead/rhythm']],
['srv-sky-crying','Stevie Ray Vaughan','The Sky Is Crying','The Sky Is Crying','blues','solo','C',['minor-pentatonic','minor-blues'],['wide bends','slow blues'],['bend','vibrato'],5,['Albert King bend','bend resolution','Texas blues'],['Albert King']],
['hendrix-little-wing','Jimi Hendrix','Little Wing','Axis: Bold as Love','rock','intro','Eb',['major-pentatonic','minor-pentatonic'],['chord embellishment','chord and melody'],['chord-embellishment','hammer-on'],4,['Hendrix chord embellishment','double-stop pentatonic','chord + melody']],
['hendrix-red-house','Jimi Hendrix','Red House','Are You Experienced','blues-rock','solo','B',['minor-pentatonic','minor-blues'],['blue note','dynamic phrasing'],['bend','vibrato'],4,['minor pentatonic','dominant blues','blue note passing tone'],['B.B. King']],
['hendrix-hey-joe','Jimi Hendrix','Hey Joe','Are You Experienced','rock','verse-fill','E',['minor-pentatonic','minor'],['melodic pedal phrase','motivic movement'],['hammer-on','slide'],3,['minor pentatonic','chord + melody']],
['hendrix-wind-cries','Jimi Hendrix','The Wind Cries Mary','Are You Experienced','rock','intro','F',['major-pentatonic','major'],['triad embellishment','voice leading'],['chord-embellishment','hammer-on'],3,['Hendrix chord embellishment','chord + melody','double-stop pentatonic'],['B.B. King']],
['hendrix-purple-haze','Jimi Hendrix','Purple Haze','Are You Experienced','blues-rock','solo','E',['minor-pentatonic','minor-blues'],['blues-rock tension','motivic repetition'],['bend','vibrato'],4,['dominant blues','minor pentatonic','octave phrase']],
['frusciante-scar-tissue','John Frusciante','Scar Tissue','Californication','rock','riff','F',['major-pentatonic','major'],['intervallic melody','open spacing'],['slide','double-stop'],3,['intervallic melody','double stops']],
['frusciante-under-bridge','John Frusciante','Under the Bridge','Blood Sugar Sex Magik','rock','intro','D',['major','major-pentatonic'],['triad embellishment','voice leading'],['chord-embellishment','hammer-on'],4,['Hendrix chord embellishment','rhythm + lead'],['Jimi Hendrix']],
['frusciante-cant-stop','John Frusciante',"Can't Stop",'By the Way','funk-rock','riff','E',['minor-pentatonic'],['muted single-note line','syncopation'],['hammer-on','pull-off'],4,['muted funk','rhythm + lead']],
['frusciante-if-ask','John Frusciante','If You Have to Ask','Blood Sugar Sex Magik','funk-rock','verse-fill','E',['minor-pentatonic','dorian'],['funk fill','rhythmic displacement'],['slide','double-stop'],4,['muted funk','double stops','rhythm + lead']],
['frusciante-dani','John Frusciante','Dani California','Stadium Arcadium','rock','solo','A',['minor-pentatonic','minor-blues'],['rock solo phrasing','dynamic build'],['bend','hammer-on'],4,['minor pentatonic','double stops']],
['slash-sweet-first','Slash',"Sweet Child O' Mine",'Appetite for Destruction','rock','solo','Eb',['major-pentatonic','minor-pentatonic'],['melodic development','bend resolution'],['bend','vibrato'],4,['major pentatonic rock','bend resolution']],
['slash-sweet-outro','Slash',"Sweet Child O' Mine",'Appetite for Destruction','rock','outro','Eb',['minor-pentatonic','minor','harmonic-minor'],['outro lead vocabulary','sequencing'],['bend','pull-off'],5,['minor pentatonic','harmonic minor rock','legato pentatonic']],
['slash-november','Slash','November Rain','Use Your Illusion I','rock','solo','C',['minor-pentatonic','minor'],['melodic bends','motivic development'],['bend','vibrato'],4,['bend resolution','legato pentatonic']],
['slash-jungle','Slash','Welcome to the Jungle','Appetite for Destruction','rock','verse-fill','Eb',['minor-pentatonic','minor-blues'],['lead punctuation','rock articulation'],['bend','double-stop'],4,['minor pentatonic','double-stop bend']],
['slash-paradise','Slash','Paradise City','Appetite for Destruction','rock','outro','G',['minor-pentatonic','minor'],['fast pentatonic sequencing','climactic phrasing'],['hammer-on','pull-off'],5,['legato pentatonic','minor pentatonic']],
['knopfler-sultans-first','Mark Knopfler','Sultans of Swing','Dire Straits','rock','solo','D',['minor-pentatonic','dorian'],['triad targeting','fingerstyle articulation'],['fingerstyle','pull-off'],5,['fingerstyle triad lead','chord-tone targeting']],
['knopfler-sultans-outro','Mark Knopfler','Sultans of Swing','Dire Straits','rock','outro','D',['minor-pentatonic','dorian'],['motif development','arpeggiated lead'],['fingerstyle','hammer-on'],5,['fingerstyle arpeggio','motif development']],
['knopfler-brothers','Mark Knopfler','Brothers in Arms','Brothers in Arms','rock','opening-fills','G#',['minor-pentatonic','minor'],['space','sustained melody'],['fingerstyle','vibrato'],3,['melodic bends','chord-tone targeting']],
['knopfler-telegraph','Mark Knopfler','Telegraph Road','Love over Gold','rock','solo','D',['minor-pentatonic','major-pentatonic'],['long-form development','melodic resolution'],['fingerstyle','bend'],5,['motif development','major pentatonic']],
['knopfler-romeo','Mark Knopfler','Romeo and Juliet','Making Movies','rock','riff','F',['major','major-pentatonic'],['melodic figure','arpeggiation'],['fingerstyle','slide'],4,['fingerstyle arpeggio','major pentatonic']],
['gary-train','Gary Clark Jr.','When My Train Pulls In','Blak and Blu','blues-rock','solo','E',['minor-pentatonic','minor-blues'],['repetition','dynamic build'],['bend','vibrato'],4,['modern blues pentatonic','fuzz phrasing','rhythmic repetition'],['B.B. King','Jimi Hendrix']],
['gary-bright','Gary Clark Jr.','Bright Lights','Blak and Blu','blues-rock','verse-fill','E',['minor-pentatonic','minor-blues'],['lead fragment','blue note'],['slide','bend'],3,['modern blues pentatonic','minor pentatonic','fuzz phrasing'],['B.B. King','Jimi Hendrix']],
['gary-numb','Gary Clark Jr.','Numb','Blak and Blu','blues-rock','solo','E',['minor-pentatonic','minor-blues'],['fuzz articulation','sustained tension'],['bend','vibrato'],4,['fuzz phrasing','modern blues pentatonic']],
['gary-next-door','Gary Clark Jr.','Next Door Neighbor Blues','Blak and Blu','blues','riff','E',['minor-pentatonic','minor-blues'],['acoustic blues','roots articulation'],['slide','fingerstyle'],3,['roots blues','slide']],
['gary-aint-messin','Gary Clark Jr.',"Ain't Messin' 'Round",'Blak and Blu','soul','verse-fill','C',['major-pentatonic','mixolydian'],['soul fill','rhythmic repetition'],['slide','double-stop'],3,['soul targeting','rhythmic repetition']]
];
const unique=<T,>(items:readonly T[])=>[...new Set(items)];
const mergeTheory=(a:VerifiedTheory|undefined,b:VerifiedTheory):VerifiedTheory=>({baseScale:b.baseScale??a?.baseScale,additionalDegrees:unique([...(a?.additionalDegrees??[]),...(b.additionalDegrees??[])]),importantDegrees:unique([...(a?.importantDegrees??[]),...(b.importantDegrees??[])]),chordShapes:unique([...(a?.chordShapes??[]),...(b.chordShapes??[])]),techniques:unique([...(a?.techniques??[]),...(b.techniques??[])])});
const base:ReferenceLick[]=seeds.map(([id,artist,song,album,style,section,originalKey,scaleCandidates,concepts,techniques,difficulty,vocabularyFamilies,influences])=>({id,artist,song,album,style,section,originalKey,transcriptionStatus:'pending',musicalContext:{scaleCandidates,description:'Contexto sugerido para escucha y análisis; pendiente de confirmar contra una transcripción.'},concepts,techniques,difficulty,vocabularyFamilies,influences,source:{type:'recording',description:`Grabación de referencia: ${artist} — ${song}. Transcripción aún no incorporada a Lisa.`}}));
for(const doc of VERIFIED_REFERENCE_LICKS){const index=base.findIndex(l=>l.artist===doc.artist&&l.song===doc.song);if(index<0){base.push({...doc,transcriptionStatus:'pending',documentation:[doc.source],source:{type:'recording',description:`Referencia estilística documentada: ${doc.artist} — ${doc.song}. Sin eventos nota por nota.`}});continue}const current=base[index];base[index]={...current,concepts:unique([...current.concepts,...doc.concepts]),techniques:unique([...current.techniques,...doc.techniques]),vocabularyFamilies:unique([...current.vocabularyFamilies,...doc.vocabularyFamilies]),musicalContext:{...current.musicalContext,...doc.musicalContext,scaleCandidates:unique([...current.musicalContext.scaleCandidates,...doc.musicalContext.scaleCandidates])},verifiedTheory:mergeTheory(current.verifiedTheory,doc.verifiedTheory),documentation:[...(current.documentation??[]),doc.source]}}
export const REFERENCE_LICKS:readonly ReferenceLick[]=base;
export const LICKS=REFERENCE_LICKS;
