import type {Difficulty,DocumentationSource,LickSection,LickStyle,Technique,VerifiedTheory} from './types';import type {ScaleKey} from '../music/scales';
export type DocumentedReference={id:string;artist:string;song:string;section:LickSection;originalKey:string;style:LickStyle;musicalContext:{scaleCandidates:ScaleKey[];chord?:string;chords?:string[];progression?:string[];description:string};verifiedTheory:VerifiedTheory;vocabularyFamilies:string[];concepts:string[];techniques:Technique[];difficulty:Difficulty;source:DocumentationSource};
const gw=(article:string,verification:DocumentationSource['verification']):DocumentationSource=>({publisher:'Guitar World',article,verification});
export const VERIFIED_REFERENCE_LICKS:readonly DocumentedReference[]=[
{id:'bb-thrill-intro',artist:'B.B. King',song:'The Thrill Is Gone',section:'intro',originalKey:'B',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic'],description:'Fraseo en B menor con extensiones y notas de color sobre la progresión.'},verifiedTheory:{baseScale:'B minor pentatonic',additionalDegrees:['2/9','7'],techniques:['bend','vibrato','slide','pull-off']},vocabularyFamilies:['BB Box','space / phrasing','targeting chord tones','minor blues vocabulary'],concepts:['fraseo vocal','tensión y resolución','espacio entre frases','notas externas a la pentatónica'],techniques:['bend','vibrato','slide','pull-off'],difficulty:2,source:gw('How to play B.B. King’s The Thrill Is Gone','editorial-analysis')},
{id:'bb-intro-space',artist:'B.B. King',song:'B.B. King intro vocabulary',section:'intro-style',originalKey:'B',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic'],description:'Ejemplo pedagógico documentado de intros con pentatónica menor y espacio.'},verifiedTheory:{baseScale:'B minor pentatonic',techniques:['bend','vibrato']},vocabularyFamilies:['BB Box','space / phrasing'],concepts:['economía de notas','silencio como parte de la frase','tensión y resolución'],techniques:['bend','vibrato'],difficulty:1,source:gw('10 B.B. King-inspired blues intro licks you need to know','editorial-analysis')},
{id:'bb-thrill-color-tones',artist:'B.B. King',song:'The Thrill Is Gone',section:'lead-phrasing',originalKey:'B',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic'],description:'Uso de notas externas a la pentatónica para ampliar el color melódico.'},verifiedTheory:{baseScale:'B minor pentatonic',additionalDegrees:['2/9','7']},vocabularyFamilies:['pentatonic extensions','targeting chord tones'],concepts:['la pentatónica como base, no como límite','notas de color','resolución melódica'],techniques:[],difficulty:2,source:gw('How to play B.B. King’s The Thrill Is Gone','editorial-analysis')},
{id:'hendrix-little-wing-em7',artist:'Jimi Hendrix',song:'Little Wing',section:'intro',originalKey:'E',style:'rock',musicalContext:{scaleCandidates:['minor-pentatonic'],chord:'Em7',description:'Trabajo chord/melody sobre una forma de Em7 alrededor de la posición 12.'},verifiedTheory:{chordShapes:['Em7'],techniques:['slide','hammer-on','pull-off','double-stop']},vocabularyFamilies:['Hendrix chord embellishment','chord + melody','double-stop pentatonic'],concepts:['mezclar acompañamiento y melodía','embellecer acordes','movimiento interno de voces'],techniques:['slide','hammer-on','pull-off','double-stop'],difficulty:3,source:gw("Examining Jimi Hendrix's Rhythm-Guitar Genius",'song-analysis')},
{id:'hendrix-little-wing-g',artist:'Jimi Hendrix',song:'Little Wing',section:'intro',originalKey:'E',style:'rock',musicalContext:{scaleCandidates:['major-pentatonic'],chord:'G',description:'G mayor en posición baja con bajo tomado con pulgar y embellishments.'},verifiedTheory:{chordShapes:['G major'],techniques:['thumb-over','hammer-on','pull-off']},vocabularyFamilies:['Hendrix chord embellishment','chord + melody'],concepts:['liberar dedos para ornamentar acordes','bajo con pulgar','voz superior melódica'],techniques:['thumb-over','hammer-on','pull-off'],difficulty:3,source:gw("Examining Jimi Hendrix's Rhythm-Guitar Genius",'song-analysis')},
{id:'hendrix-wind-cries-mary',artist:'Jimi Hendrix',song:'The Wind Cries Mary',section:'rhythm-embellishment',originalKey:'F',style:'rock',musicalContext:{scaleCandidates:['major-pentatonic'],description:'Uso de voicings y embellishments alrededor de acordes, integrando melodía y ritmo.'},verifiedTheory:{techniques:['hammer-on','pull-off','double-stop']},vocabularyFamilies:['Hendrix chord embellishment','rhythm + lead'],concepts:['ornamentación de voicings','frases dentro del acompañamiento'],techniques:['hammer-on','pull-off','double-stop'],difficulty:3,source:gw("Examining Jimi Hendrix's Rhythm-Guitar Genius",'editorial-analysis')},
{id:'srv-pride-shuffle',artist:'Stevie Ray Vaughan',song:'Pride and Joy',section:'main-groove',originalKey:'E',style:'blues-rock',musicalContext:{scaleCandidates:['minor-pentatonic'],progression:['I7','IV7','V7'],description:'Texas shuffle en E ejecutado con guitarra afinada medio tono abajo (sonido Eb).'},verifiedTheory:{baseScale:'E minor pentatonic',techniques:['shuffle','muting','upstroke chord accents','single-note fills']},vocabularyFamilies:['Texas shuffle','rhythm + lead','minor pentatonic fills'],concepts:['línea de bajo + acordes','fills pentatónicos entre el groove','muting de ambas manos'],techniques:['shuffle','muting','chord-accents','single-note-fills'],difficulty:4,source:gw('How to Play Stevie Ray Vaughan’s Pride and Joy Shuffle','song-analysis')},
{id:'srv-lenny-embellishment',artist:'Stevie Ray Vaughan',song:'Lenny',section:'lead-rhythm',originalKey:'E',style:'blues',musicalContext:{scaleCandidates:['major-pentatonic'],chords:['Emaj13','Amaj9'],description:'Lenguaje Hendrix aplicado a voicings extendidos y frases melódicas.'},verifiedTheory:{baseScale:'E major pentatonic',additionalDegrees:['b3 passing tone'],techniques:['hammer-on','pull-off','slide','double-stop']},vocabularyFamilies:['Hendrix chord embellishment','major pentatonic','major/minor mixture'],concepts:['penta mayor con b3 de paso','voicings extendidos','fraseo líquido'],techniques:['hammer-on','pull-off','slide','double-stop'],difficulty:4,source:gw('Stevie Ray Vaughan’s 10 greatest guitar moments','editorial-analysis')},
{id:'srv-sky-albert-bend',artist:'Stevie Ray Vaughan',song:'The Sky Is Crying',section:'lead',originalKey:'C',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic'],description:'Fraseo inspirado en el lenguaje de bending de Albert King.'},verifiedTheory:{techniques:['whole-step bend','wide bend','vibrato']},vocabularyFamilies:['Albert King bend','vocal bending'],concepts:['afinación precisa del bend','fraseo vocal','posición clásica de Albert King'],techniques:['bend','wide-bend','vibrato'],difficulty:3,source:gw('Stevie Ray Vaughan defined the sound of contemporary blues guitar','editorial-analysis')},
{id:'mayer-gravity-intervals',artist:'John Mayer',song:'Gravity',section:'lead-phrasing',originalKey:'G',style:'blues',musicalContext:{scaleCandidates:['major-pentatonic','minor-pentatonic'],description:'Fraseo melódico con énfasis en intervalos y uso prominente de la sexta.'},verifiedTheory:{importantDegrees:['6'],techniques:['bend','slide','vibrato']},vocabularyFamilies:['lyrical blues','intervallic melody','space / phrasing'],concepts:['uso de la sexta','timing libre respecto de la grilla','melodía por encima de patrón pentatónico'],techniques:['bend','slide','vibrato'],difficulty:2,source:gw('How to play gospel blues guitar','editorial-analysis')},
{id:'mayer-slow-dancing-double-stops',artist:'John Mayer',song:'Slow Dancing in a Burning Room',section:'intro-and-fills',originalKey:'C#',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic'],description:'Enfoque pentatónico con double stops y ornamentaciones melódicas.'},verifiedTheory:{techniques:['double-stop','slide','hammer-on']},vocabularyFamilies:['double-stop pentatonic','Hendrix-derived embellishment','rhythm + lead'],concepts:['double stops','mezcla de acompañamiento y lead','fraseo pentatónico'],techniques:['double-stop','slide','hammer-on'],difficulty:3,source:gw('How to play gospel blues guitar','editorial-analysis')},
{id:'mayer-bb-phrasing',artist:'John Mayer',song:'John Mayer blues vocabulary',section:'style-reference',originalKey:'A',style:'blues',musicalContext:{scaleCandidates:['minor-pentatonic','major-pentatonic'],description:'Vocabulario de frases cortas separadas por silencios y lenguaje relacionado con B.B. King.'},verifiedTheory:{techniques:['quarter-tone bend','bend','vibrato']},vocabularyFamilies:['BB Box','space / phrasing','minor/major blues mixture'],concepts:['frases cortas','silencio','microbends','resolución sobre chord tones'],techniques:['quarter-tone-bend','bend','vibrato'],difficulty:2,source:gw('John Mayer guitar lesson: 12 tips','style-analysis')}
];
