import type {CourseLevel,Lesson,LessonStep,ValidationRule} from './lessonTypes';
const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const explain=(id:string,title:string,body:string,lines?:string[]):LessonStep=>({id,type:'explanation',title,body,lines});
const exercise=(id:string,title:string,prompt:string,validation:ValidationRule,options:string[],success:string,hint:string,kind:'multiple-choice'|'note-selection'|'order'|'fretboard'='multiple-choice'):LessonStep=>({id,type:'exercise',title,prompt,validation,options,success,hint,exercise:kind});
const summary=(id:string,body:string):LessonStep=>({id,type:'summary',title:'Idea clave',body});
const lesson=(id:string,title:string,description:string,steps:LessonStep[],prerequisites:string[]=[],explore?:Lesson['explore']):Lesson=>({id,title,description,estimatedMinutes:5,prerequisites,steps,explore});
const levels:CourseLevel[]=[
{id:'mapa',title:'Nivel 1 · El mapa musical',description:'Notas, distancias y guitarra.',lessons:[
lesson('twelve-notes','Las 12 notas','El alfabeto cromático.',[explain('a','Una octava, doce alturas','Después de B volvemos a C en otra octava.',NOTES),exercise('b','Medí la distancia','¿Cuántos semitonos hay entre C y D?',{type:'interval',from:'C',to:'D'},['1','2','3'],'Correcto: C→C#→D son dos semitonos.','Contá cada paso cromático.'),summary('c','Sostenidos y bemoles pueden nombrar una misma altura.')]),
lesson('tones','Tono y semitono','Las dos distancias básicas.',[explain('a','Pasos vecinos','E→F y B→C son semitonos; C→D es un tono.'),exercise('b','Compará','¿Cuántos semitonos hay entre E y F?',{type:'interval',from:'E',to:'F'},['1','2','3'],'Correcto: no hay una tecla intermedia.','Buscá si existe una nota cromática entre ambas.'),summary('c','Un tono equivale a dos semitonos.')],['twelve-notes']),
lesson('fretboard-notes','Encontrar notas en el mástil','La misma nota aparece en varias cuerdas.',[explain('a','El mapa se repite','Cada traste sube un semitono. Marcá posiciones, no memorices una sola forma.'),exercise('b','Encontrá C','Marcá todos los C entre los trastes 0 y 12.',{type:'exact',answer:['C']},NOTES,'Correcto: reconociste todas las posiciones visibles.','Recordá que el traste 12 repite la cuerda al aire.','fretboard'),summary('c','Una pitch class puede aparecer en múltiples registros.')],['tones']),
lesson('intervals','Intervalos','Nombrar la distancia entre notas.',[explain('a','De 1 a 7','Cada distancia tiene semitonos, grado y cualidad.', ['1 · 0','b2 · 1','2 · 2','b3 · 3','3 · 4','4 · 5','b5/#4 · 6','5 · 7','b6 · 8','6 · 9','b7 · 10','7 · 11']),exercise('b','B hacia D','¿Cuántos semitonos hay?',{type:'interval',from:'B',to:'D'},['2','3','4'],'Correcto: B–D es una tercera menor.','Contá B→C→C#→D.'),summary('c','Los intervalos describen relaciones, independientemente del registro.')],['fretboard-notes'])]},
{id:'major',title:'Nivel 2 · Escala mayor',description:'Fórmula, grados y mástil.',lessons:[
lesson('major-scale','Construir la escala mayor','Aplicar 2–2–1–2–2–2–1.',[explain('a','La fórmula mayor','Avanzá T T S T T T S desde la tónica.', ['2 · 2 · 1 · 2 · 2 · 2 · 1']),exercise('b','Construí G mayor','Seleccioná sus siete notas.',{type:'scale-notes',root:'G',scaleKey:'major'},NOTES,'Correcto: el motor obtiene G A B C D E F# desde la fórmula.','Sólo una nota lleva sostenido.','note-selection'),summary('c','La fórmula se transporta a cualquier tónica.')],['intervals'],{root:'G',scaleKey:'major'}),
lesson('scale-degrees','Grados de la escala','La función de cada posición.',[explain('a','Números reutilizables','En C mayor: C D E F G A B corresponde a 1 2 3 4 5 6 7.'),exercise('b','Sexto grado','¿Cuál es el 6° grado de G mayor?',{type:'exact',answer:'E'},['D','E','F#'],'Correcto: G(1), A(2), B(3), C(4), D(5), E(6).','Contá desde G incluyendo la tónica.'),summary('c','Los grados se conservan al transportar.')],['major-scale']),
lesson('major-fretboard','Escala mayor en el mástil','Ver grados en todas las cuerdas.',[explain('a','Forma y función','La tercera de C mayor es E; aparece en varias posiciones.'),exercise('b','Encontrá la tercera','Seleccioná E como tercera de C mayor.',{type:'exact',answer:'E'},NOTES,'Correcto: E es el tercer grado de C mayor.','C=1, D=2…','note-selection'),summary('c','El grado explica qué hace la nota dentro de la escala.')],['scale-degrees'],{root:'C',scaleKey:'major'})]},
{id:'chords',title:'Nivel 3 · Construcción de acordes',description:'Triadas, cualidades e inversiones.',lessons:[
lesson('triads','¿Qué es una triada?','Construir por terceras.',[explain('a','Una sí y una no','Desde C mayor, 1–3–5 produce C–E–G.'),exercise('b','Triada desde D','Elegí las notas de D menor.',{type:'chord-notes',root:'D',quality:'minor'},NOTES,'Correcto: D–F–A toma notas alternadas de C mayor.','Empezá en D y salteá una nota cada vez.','note-selection'),summary('c','Una triada apila dos terceras.')],['major-fretboard']),
lesson('major-minor','Mayor vs menor','La tercera define el color básico.',[explain('a','Compará','C–E–G = 1 3 5. C–Eb–G = 1 b3 5.'),exercise('b','Identificá','¿Qué cualidad tiene C–Eb–G?',{type:'exact',answer:'menor'},['mayor','menor','disminuido'],'Correcto: la tercera menor determina la cualidad.','Medí C→Eb.'),summary('c','Mayor y menor comparten 1 y 5; cambia la tercera.')],['triads']),
lesson('diminished','Acorde disminuido','Dos terceras menores apiladas.',[explain('a','B–D–F','Su fórmula es 1 b3 b5.'),exercise('b','Construí B°','Seleccioná sus notas.',{type:'chord-notes',root:'B',quality:'diminished'},NOTES,'Correcto: B–D son 3 semitonos y B–F son 6.','La quinta está un semitono debajo de la quinta justa.','note-selection'),exercise('c','Explicá la cualidad','¿Qué intervalo vuelve disminuido a B°?',{type:'exact',answer:'b5'},['5','b5','6'],'Correcto: la quinta disminuida es b5.','Medí B→F.'),summary('d','Disminuido = 1 b3 b5.')],['major-minor'])]},
{id:'arpeggios',title:'Nivel 4 · Arpegios',description:'Del acorde a una línea melódica. Roadmap: triadas, séptimas, extensiones, cambios, guide tones y conexiones.',lessons:[
lesson('arpeggio-intro','¿Qué es un arpegio?','Recorrer melódicamente las notas de un acorde.',[explain('a','Mismas notas, otro gesto','Acorde: C + E + G simultáneamente. Arpegio: C → E → G.'),exercise('b','Arpegio de Dm','Seleccioná sus notas.',{type:'chord-notes',root:'D',quality:'minor'},NOTES,'Correcto: D–F–A es el arpegio de Dm.','Derivalo de 1 b3 5.','note-selection'),summary('c','Un voicing dispone voces; un arpegio recorre las notas como línea.')],['diminished']),
lesson('seventh-arpeggios','Arpegios de séptima','Sumar la séptima a la triada.',[explain('a','Cuatro chord tones','G7 contiene G B D F: 1 3 5 b7.'),exercise('b','Arpegio de Dm7','Construí el arpegio de Dm7.',{type:'chord-notes',root:'D',quality:'minor7'},NOTES,'Correcto: D–F–A–C.','Partí de Dm y agregá la b7.','note-selection'),summary('c','La 3ª y la 7ª son guide tones: describen con claridad la cualidad.')],['arpeggio-intro'])]},
{id:'harmony',title:'Nivel 5 · Armonización',description:'Acordes dentro de una tonalidad.',lessons:[
lesson('harmonize-major','Armonizar C mayor','Construir una triada desde cada grado.',[explain('a','Terceras diatónicas','Usá sólo C D E F G A B y tomá una nota sí y una no.'),exercise('b','Construí C','Elegí C–E–G.',{type:'chord-notes',root:'C',quality:'major'},NOTES,'Correcto: C–E–G.','Usá 1–3–5.','note-selection'),exercise('c','Construí Dm','Elegí D–F–A.',{type:'chord-notes',root:'D',quality:'minor'},NOTES,'Correcto: el ii grado es menor.','Usá sólo notas de C mayor.','note-selection'),exercise('d','Construí B°','Elegí B–D–F.',{type:'chord-notes',root:'B',quality:'diminished'},NOTES,'Correcto: el vii grado es disminuido.','La quinta de B queda disminuida.','note-selection'),summary('e','C Dm Em F G Am B° corresponde a I ii iii IV V vi vii°.')],['diminished'],{root:'C',scaleKey:'major'}),
lesson('harmony-pattern','Descubrir el patrón','La secuencia de cualidades mayor.',[explain('a','Patrón transportable','Mayor · menor · menor · Mayor · Mayor · menor · disminuido.'),exercise('b','VI en G mayor','¿Qué calidad tiene?',{type:'harmony-quality',root:'G',scaleKey:'major',degree:6},['Mayor','menor','disminuido'],'Correcto: el VI grado de la escala mayor es menor.','Usá el sexto lugar del patrón.'),summary('c','Los nombres cambian; el patrón permanece.')],['harmonize-major']),
lesson('progressions-intro','Introducción a progresiones','Ordenar funciones armónicas.',[explain('a','Grados como receta','I–IV–V se transporta sin perder su función.'),exercise('b','I–IV–V en G','Seleccioná los tres acordes en orden.',{type:'exact',answer:['G','C','D']},['G','Am','B','C','D','Em'],'Correcto: G–C–D.','Buscá los grados 1, 4 y 5.','order'),summary('c','Una progresión describe relaciones, no una tonalidad fija.')],['harmony-pattern'],{root:'G',scaleKey:'major'}),
lesson('relative-minor','La menor relativa','Mismas notas, otro centro.',[explain('a','C mayor y A menor','C D E F G A B y A B C D E F G comparten el material.'),exercise('b','Relativa de G','¿Cuál es la relativa menor?',{type:'exact',answer:'E'},['D','E','F#'],'Correcto: E es el sexto grado de G mayor.','Buscá el VI grado.'),summary('c','Cambiar el centro tonal cambia la percepción aunque las notas coincidan.')],['progressions-intro']),
lesson('modes-intro','Introducción a modos','Mismas notas, nuevo centro modal.',[explain('a','De C mayor a G','G A B C D E F usa las notas de C mayor, pero G se vuelve el centro.'),{id:'b',type:'comparison',title:'G mayor vs G Mixolidio',body:'El conjunto cambia sólo en la séptima.',lines:['G mayor: G A B C D E F#','G Mixolidio: G A B C D E F','7 → b7']},exercise('c','¿Qué cambió?', 'Elegí el grado característico.',{type:'exact',answer:'b7'},['b3','b7','#4'],'Correcto: Mixolidio tiene séptima menor.','Compará F# con F.'),summary('d','Un modo se entiende por su centro y sus grados característicos.')],['relative-minor'],{root:'G',scaleKey:'mixolydian'})]},
{id:'pentatonic',title:'Nivel 6 · Pentatónicas y blues',description:'Roadmap: pentatónicas, blue note y mezcla.',roadmapOnly:true,lessons:[]},{id:'modes',title:'Nivel 7 · Modos',description:'Roadmap: los siete modos y sus rasgos.',roadmapOnly:true,lessons:[]},{id:'sevenths',title:'Nivel 8 · Acordes de séptima',description:'Roadmap: maj7, m7, dominante y disminuidos.',roadmapOnly:true,lessons:[]},{id:'applied',title:'Nivel 9 · Armonía aplicada',description:'Roadmap: tensiones, voicings y notas objetivo.',roadmapOnly:true,lessons:[]}
];
export const CURRICULUM:readonly CourseLevel[]=levels;export const IMPLEMENTED_LESSONS=levels.flatMap(l=>l.lessons);export function getLesson(id:string){return IMPLEMENTED_LESSONS.find(l=>l.id===id)}
