export type LessonGuidance={goal:string;connection:string;application:string};
export const LESSON_GUIDANCE:Record<string,LessonGuidance>={
 'arpeggio-intro':{goal:'Distinguir acorde y arpegio.',application:'Construir una triada como línea melódica.',connection:'Las notas vienen del mismo motor de acordes.'},
 'seventh-arpeggios':{goal:'Agregar la séptima al recorrido.',application:'Practicar guide tones sobre cambios.',connection:'La 3ª y la 7ª revelan la cualidad del acorde.'},
 'twelve-notes':{goal:'Reconocer el ciclo de doce alturas que usa toda la música occidental.',connection:'Es el mapa base: escalas, acordes e intervalos son selecciones y distancias dentro de este ciclo.',application:'Te permite encontrar una nota aunque cambie de octava o instrumento.'},
 tones:{goal:'Medir distancias pequeñas en semitonos y tonos.',connection:'Ahora que conocés las notas, empezás a medir el espacio que hay entre ellas.',application:'Es la unidad con la que se construyen escalas, intervalos y acordes.'},
 'fretboard-notes':{goal:'Trasladar el ciclo cromático al mástil.',connection:'Cada traste avanza exactamente un semitono; por eso una misma nota reaparece en distintas cuerdas.',application:'Ubicar notas objetivo sin depender solamente de dibujos o patrones.'},
 intervals:{goal:'Nombrar la relación entre dos notas.',connection:'Un intervalo convierte una cantidad de semitonos en una función musical reconocible.',application:'Entender fórmulas como 1–3–5, tensiones y movimientos melódicos.'},
 'major-scale':{goal:'Construir una escala mayor desde cualquier tónica.',connection:'La escala es una secuencia concreta de tonos y semitonos.',application:'Crear el material de notas del que surgirán grados, melodías y acordes.'},
 'scale-degrees':{goal:'Pensar las notas por su función y no sólo por su nombre.',connection:'La misma fórmula puede transportarse porque 1, 2, 3… describen posiciones relativas.',application:'Transportar ideas musicales y reconocer tensión o reposo.'},
 'major-fretboard':{goal:'Ver los grados de una escala en todo el instrumento.',connection:'Un mismo grado aparece en varios registros, pero conserva su función.',application:'Elegir notas por lo que hacen dentro de la tonalidad.'},
 triads:{goal:'Construir acordes tomando 1, 3 y 5.',connection:'Los acordes aparecen al seleccionar notas alternadas de una escala.',application:'Dejar de memorizar nombres aislados y poder reconstruirlos.'},
 'major-minor':{goal:'Escuchar y reconocer el efecto de la tercera.',connection:'Mayor y menor mantienen raíz y quinta; la tercera define el color básico.',application:'Modificar o identificar rápidamente la cualidad de un acorde.'},
 diminished:{goal:'Entender la tensión del acorde disminuido.',connection:'Al bajar la quinta de una triada menor aparece la fórmula 1–b3–b5.',application:'Reconocer el acorde inestable que surge en la armonización mayor.'},
 'harmonize-major':{goal:'Construir un acorde sobre cada grado de la escala.',connection:'Aplicás la construcción de triadas sin salir de las siete notas disponibles.',application:'Obtener la familia de acordes de una tonalidad.'},
 'harmony-pattern':{goal:'Reconocer el patrón de cualidades de la escala mayor.',connection:'Las notas cambian al transportar, pero el orden Mayor–menor–menor… se conserva.',application:'Encontrar acordes diatónicos rápidamente en cualquier tonalidad.'},
 'progressions-intro':{goal:'Organizar acordes como funciones que generan movimiento.',connection:'Los números romanos describen un recorrido armónico transportable.',application:'Construir progresiones y entender por qué ciertos acordes conducen a otros.'},
 'relative-minor':{goal:'Distinguir material compartido de centro tonal.',connection:'Dos tonalidades pueden usar las mismas notas y sentirse distintas por su punto de reposo.',application:'Moverte entre mayor y menor sin cambiar la colección de notas.'},
 'modes-intro':{goal:'Entender un modo como escala, centro y grado característico.',connection:'Cambiar el centro reorganiza la función de notas conocidas.',application:'Comparar colores modales y elegirlos con intención.'}
};
