import type {TheoryArticle,TheoryCategory,TheoryLevel} from '../types';

const text=(title:string,body:string)=>({type:'text' as const,title,body});
const explanations:Record<TheoryCategory,(title:string)=>ReturnType<typeof text>[]>= {
 fundamentals:title=>[text('Cómo entenderlo',`${title} forma parte del vocabulario con el que nombramos lo que escuchamos. Conviene distinguir la altura real, su nombre escrito y la función que cumple respecto de un centro: pueden coincidir, pero no son la misma cosa.`),text('Qué observar',`Buscá ${title.toLowerCase()} en ejemplos concretos y comprobá qué permanece igual al cambiar de tonalidad o registro. Esa separación entre nombre, sonido y función evita memorizar reglas sin contexto.`)],
 intervals:title=>[text('Cómo se escucha',`${title} no describe una nota aislada, sino una relación entre dos alturas. Conserva su distancia al transportarse, aunque su efecto cambia si aparece melódicamente, dentro de un acorde o en otro registro.`),text('Cómo analizarlo',`Contá primero las letras para determinar el número y después los semitonos para determinar la cualidad. En ${title.toLowerCase()}, ambas partes del nombre son necesarias: una escritura enarmónica puede sonar igual y cumplir otra función.`)],
 scales:title=>[text('Cómo entenderla',`${title} es un conjunto de relaciones respecto de una tónica, no solamente una lista ascendente. La fórmula muestra qué grados son estables, cuáles aportan color y dónde aparecen tonos o semitonos.`),text('Cómo reconocerla',`Mantené audible la tónica mientras recorrés ${title.toLowerCase()} y aislá sus grados característicos. Tocar las notas correctas sin afirmar el centro puede producir una lectura musical diferente.`)],
 modes:title=>[text('Centro y color',`${title} se reconoce por la combinación de un centro tonal claro y grados característicos. Compartir notas con una escala madre explica su construcción, pero no determina por sí solo cómo se escucha.`),text('Cómo probarlo',`Usá un pedal que sostenga la tónica y destacá el grado que diferencia a ${title.toLowerCase()} del modo mayor o menor paralelo. Observá dónde descansan las frases, no sólo qué notas contienen.`)],
 chords:title=>[text('Cómo se construye',`${title} se entiende como una fórmula de intervalos desde la fundamental. Esa fórmula permanece al transportar el acorde; las notas concretas, el registro y la disposición de las voces pueden cambiar.`),text('Qué escuchar',`Separá fundamental, tercera, quinta y extensiones de ${title.toLowerCase()}. La tercera suele definir la cualidad básica, mientras séptimas y tensiones precisan color y función; otro bajo o voicing puede cambiar mucho el resultado.`)],
 harmony:title=>[text('Función en contexto',`${title} describe una relación en el tiempo: importa de dónde viene, hacia dónde se dirige y qué nota se percibe como tónica. Un acorde aislado rara vez alcanza para determinar toda su función.`),text('Cómo analizarlo',`Reducí primero la progresión a grados y observá bajos, notas comunes y movimientos por semitono. Después escuchá cómo ${title.toLowerCase()} modifica la expectativa de reposo, preparación o resolución.`)],
 'advanced-harmony':title=>[text('Mecanismo',`${title} introduce color o dirección al reinterpretar temporalmente notas y acordes. La etiqueta sirve sólo si explica una conexión audible; una alteración cromática aislada no demuestra por sí misma el recurso.`),text('Cómo comprobarlo',`Compará una versión diatónica con otra que use ${title.toLowerCase()}. Seguí cada voz, identificá las notas ajenas y verificá si crean tonicización, intercambio, sustitución o simplemente movimiento cromático.`)],
 improvisation:title=>[text('Dentro de una línea',`${title} relaciona melodía, pulso y armonía en tiempo real. Su valor no depende de usarlo constantemente, sino de colocarlo con intención y resolver o sostener sus tensiones de manera audible.`),text('Cómo practicarlo',`Aplicá ${title.toLowerCase()} sobre un acorde y luego sobre dos acordes que contrasten. Limitá primero el ritmo para escuchar las alturas; después variá registro, dirección, articulación y punto de llegada.`)],
 rhythm:title=>[text('Cómo se percibe',`${title} organiza expectativas en el tiempo. No vive sólo en la notación: surge de la relación entre pulso, acento, subdivisión, duración y silencio.`),text('Cómo practicarlo',`Marcá un pulso estable y vocalizá ${title.toLowerCase()} antes de tocarlo. Alterná entre mantener el pulso y ejecutar la figura; si ambos se confunden, bajá el tempo y simplificá la subdivisión.`)],
 melody:title=>[text('Función melódica',`${title} describe cómo una línea crea identidad y dirección. La altura importa, pero también el ritmo, el contorno, la repetición y el lugar que ocupa cada nota dentro de la frase.`),text('Qué observar',`Cantá una frase corta y localizá ${title.toLowerCase()} sin mirar primero la escala. Después modificá un solo elemento para escuchar qué aporta a la continuidad, la tensión o el cierre.`)],
 composition:title=>[text('Decisión compositiva',`${title} organiza material para que una idea tenga dirección y sea reconocible. No es una plantilla obligatoria: es una variable que puede mantenerse estable o cambiar para producir contraste.`),text('Cómo explorarlo',`Creá dos versiones breves que difieran únicamente en ${title.toLowerCase()}. Compararlas permite escuchar su efecto sobre la energía, la memoria y la forma sin confundirlo con otros cambios simultáneos.`)]
};
const entry=(id:string,title:string,category:TheoryCategory,summary:string,aliases:string[]=[],level:TheoryLevel='basic'):TheoryArticle=>({id,title,category,summary,aliases,level,sections:explanations[category](title)});

export const CORE_ARTICLES:TheoryArticle[]=[
entry('twelve-notes','Las 12 notas','fundamentals','La octava occidental se divide en doce alturas; después el ciclo vuelve a empezar en otro registro.',['cromatismo','notas cromáticas']),
entry('accidentals','Alteraciones','fundamentals','Sostenidos, bemoles y becuadros modifican la altura escrita de una nota.',['sostenido','bemol','#','b']),
entry('enharmony','Enarmonía','fundamentals','Dos nombres distintos pueden representar la misma altura, como C# y Db, aunque su escritura revele funciones diferentes.',['enarmonia','C# Db']),
entry('semitone','Semitono','fundamentals','La distancia más pequeña del sistema temperado; en guitarra equivale a un traste.',['medio tono']),
entry('whole-tone','Tono','fundamentals','Distancia de dos semitonos, equivalente a dos trastes en guitarra.',['tono entero']),
entry('octave','Octava','fundamentals','La repetición de una nota a doce semitonos, con frecuencia doble o mitad.',['8va']),
entry('degrees','Grados','fundamentals','Números que describen la posición de una nota respecto de una tónica.',['grado de escala','1 2 3']),
entry('tonic','Tónica','fundamentals','Nota que se percibe como hogar o punto de reposo.',['root','fundamental']),
entry('key','Tonalidad','fundamentals','Organización de notas y acordes alrededor de un centro tonal, generalmente mayor o menor.',['key','tonalidad mayor','tonalidad menor']),
entry('tonal-center','Centro tonal','fundamentals','Altura que el oído interpreta como centro, incluso cuando varias escalas comparten notas.',['centro modal']),
entry('key-signature','Armadura','fundamentals','Conjunto de alteraciones escrito al comienzo del pentagrama para indicar el material tonal habitual.',['armadura de clave']),
entry('circle-fifths','Círculo de quintas','fundamentals','Mapa de tonalidades ordenadas por quintas que muestra armaduras, cercanía y relaciones relativas.',['circle of fifths']),
entry('interval','Qué es un intervalo','intervals','Un intervalo mide la distancia y la relación funcional entre dos notas.',['intervalo']),
...['Unísono','Segunda menor','Segunda mayor','Tercera menor','Tercera mayor','Cuarta justa','Tritono','Quinta justa','Sexta menor','Sexta mayor','Séptima menor','Séptima mayor'].map((n,i)=>entry(['unison','minor-second','major-second','minor-third','major-third','perfect-fourth','tritone','perfect-fifth','minor-sixth','major-sixth','minor-seventh','major-seventh'][i],n,'intervals',`${n} describe una distancia específica entre dos alturas y su color armónico.`,i===3?['b3','minor third','3m']:i===10?['b7','minor seventh']:[])),
entry('compound-intervals','Intervalos compuestos','intervals','Intervalos mayores que una octava; una novena, por ejemplo, es una segunda más una octava.'),
entry('interval-inversion','Inversión de intervalos','intervals','Al invertir un intervalo sus números suman nueve y mayor cambia por menor; justo permanece justo.'),
entry('consonance-dissonance','Consonancia y disonancia','intervals','Percepciones de estabilidad y fricción que cambian según registro, timbre, estilo y contexto.'),
entry('scale','Qué es una escala','scales','Una colección ordenada de alturas respecto de una tónica.',['escala']),
entry('chromatic-scale','Escala cromática','scales','Contiene las doce notas separadas por semitonos.'),entry('diminished-scale','Escala disminuida','scales','Escala simétrica de ocho notas que alterna tonos y semitonos.',['octatónica'],'advanced'),entry('whole-tone-scale','Escala de tonos enteros','scales','Escala simétrica de seis notas separadas siempre por tonos.',['whole tone'],'intermediate'),
entry('mode','Qué es un modo','modes','Un modo organiza intervalos alrededor de un centro tonal con un color característico.',['modos']),entry('parent-scale','Escala madre','modes','Escala que comparte el mismo conjunto de notas con un modo, sin determinar necesariamente su centro tonal.'),entry('modal-center','Centro tonal modal','modes','Nota que debe sentirse como hogar para que el material compartido se perciba modal.'),
...['Jónico','Dórico','Frigio','Lidio','Eólico','Locrio'].map((n,i)=>entry(['ionian','dorian','phrygian','lydian','aeolian','locrian'][i],n,'modes',`${n} es uno de los siete modos diatónicos; su identidad surge del centro y de sus grados característicos.`,[],i===0?'basic':'intermediate')),
entry('characteristic-notes','Notas características','modes','Grados que distinguen con claridad un modo de otros con la misma cualidad básica.'),entry('hearing-modes','Cómo escuchar un modo','modes','Sostené o repetí la tónica y contrastá el grado característico para afirmar el centro.'),entry('modal-progressions','Progresiones modales','modes','Progresiones que afirman una tónica modal y destacan sus grados característicos.'),entry('mode-vs-key','Modo y tonalidad','modes','Compartir notas no equivale a compartir centro ni función armónica.'),
entry('chord','Qué es un acorde','chords','Conjunto de notas entendido como una unidad armónica.',['acorde']),entry('triads','Triadas','chords','Acordes de tres notas construidos habitualmente con fundamental, tercera y quinta.',['tríadas']),entry('inversions','Inversiones','chords','Reordenamientos donde una nota distinta de la fundamental aparece en el bajo.'),entry('seventh-chords','Acordes de séptima','chords','Triadas ampliadas con una séptima; la 3ª y la 7ª definen gran parte de su función.'),
...['Mayor','Menor','Aumentado','Maj7','m7','m7b5','dim7','Acordes de sexta','Sus2','Sus4','Add9','Acordes de novena','Acordes 11','Acordes 13','Alteraciones','Slash chords','Extensiones','Omisión de notas','Voicings'].map((n,i)=>entry(['major-chord','minor-chord','augmented-triad','maj7','m7','m7b5','dim7','sixth-chords','sus2','sus4','add9','ninth-chords','eleventh-chords','thirteenth-chords','altered-chords','slash-chords','extensions','note-omission','voicings'][i],n,'chords',`${n} describe una estructura o disposición específica de voces dentro de un acorde.`,n==='Sus4'?['sus','suspended']:n==='Add9'?['add 9']:[],'intermediate')),
entry('harmonization','Armonización','harmony','Proceso de construir acordes compatibles con una melodía o escala.',['armonizar']),entry('major-harmonization','Armonización de la escala mayor','harmony','Construye un acorde diatónico desde cada grado de la escala mayor.'),entry('minor-harmonization','Armonización menor','harmony','La armonía menor combina con frecuencia material natural, armónico y melódico según la dirección buscada.'),entry('roman-numerals','Grados romanos','harmony','Símbolos que expresan acordes por su función transportable: I, ii, V, etc.'),entry('harmonic-function','Función armónica','harmony','Describe tendencia y estabilidad: tónica, predominante y dominante.',['funcion tonal']),entry('predominant','Predominante','harmony','Función que suele alejarse de tónica y preparar la dominante.'),entry('dominant-function','Dominante','harmony','Función de máxima dirección hacia la tónica; no es sinónimo de cualquier acorde 7.',['función dominante']),entry('resolution','Resolución','harmony','Movimiento desde una tensión hacia una sonoridad comparativamente estable.'),entry('tension-release','Tensión y reposo','harmony','Contraste perceptivo que articula dirección y forma musical.'),entry('cadences','Cadencias','harmony','Gestos armónicos que puntúan, suspenden o cierran frases.'),...['Cadencia auténtica','Cadencia plagal','Semicadencia','Cadencia rota'].map((n,i)=>entry(['authentic-cadence','plagal-cadence','half-cadence','deceptive-cadence'][i],n,'harmony',`${n} es un patrón de cierre definido por el destino y la fuerza de sus funciones.`)),entry('progressions','Progresiones','harmony','Secuencias de acordes cuyo orden crea dirección y forma.'),...['I–IV–V','ii–V–I','I–V–vi–IV'].map((n,i)=>entry(['one-four-five','two-five-one','one-five-six-four'][i],n,'harmony',`${n} es una progresión reutilizable en cualquier tonalidad; sus grados conservan relaciones funcionales.`,[n.replace(/–/g,'-')])) ,entry('applied-fifths','Círculo de quintas aplicado','harmony','El movimiento por quintas encadena resoluciones y permite planear progresiones.'),
...['Tonicización','Modulación','Modulación por acorde pivote','Sustitución tritonal','Disminuidos de paso','Dominantes sustitutos','Backdoor dominant','Movimiento cromático','Pedal tones','Ostinato armónico','Reharmonización básica'].map((n,i)=>entry(['tonicization','modulation','pivot-modulation','tritone-substitution','passing-diminished','substitute-dominants','backdoor-dominant','chromatic-motion','pedal-tones','harmonic-ostinato','reharmonization'][i],n,'advanced-harmony',`${n} amplía el vocabulario tonal mediante dirección, color o reinterpretación contextual.`,[],i<1?'intermediate':'advanced')),
...['Target notes','Escala global vs seguir acordes','Relación acorde–escala','Pentatónica sobre acordes','Mezcla pentatónica mayor/menor','Notas de aproximación','Cromatismos','Passing tones','Enclosures','Arpegios sobre cambios','Resolución melódica','Motivos','Desarrollo motívico','Fraseo','Espacio y silencio'].map((n,i)=>entry(['target-notes','global-vs-changes','chord-scale','pentatonic-over-chords','pentatonic-mix','approach-notes','chromaticism','passing-tones','enclosures','arpeggios-changes','melodic-resolution','motifs','motivic-development','phrasing','space'][i],n,'improvisation',`${n} es un recurso para construir líneas conectadas con la armonía y con una intención audible.`,[],i>6?'intermediate':'basic')),
...['Pulso','Tempo','BPM','Compás','4/4','3/4','6/8','Figuras rítmicas','Subdivisión','Corcheas','Semicorcheas','Tresillos','Swing','Shuffle','Síncopa','Contratiempo','Polirritmia básica'].map((n,i)=>entry(['pulse','tempo','bpm','meter','four-four','three-four','six-eight','note-values','subdivision','eighth-notes','sixteenth-notes','triplets','swing','shuffle','syncopation','offbeat','basic-polyrhythm'][i],n,'rhythm',`${n} organiza el tiempo musical y modifica cómo se perciben los mismos sonidos.`,[],i>14?'intermediate':'basic')),
...['Qué es una melodía','Motivo','Frase','Contorno melódico','Repetición','Variación','Secuencia','Tensión melódica','Notas estructurales','Notas de paso','Aproximaciones cromáticas'].map((n,i)=>entry(['melody','melodic-motif','phrase','contour','repetition','variation','sequence','melodic-tension','structural-notes','melodic-passing-notes','chromatic-approaches'][i],n,'melody',`${n} ayuda a describir cómo una línea adquiere identidad, dirección y respiración.`)),
...['Progresión para componer','Melodía al componer','Ritmo armónico','Forma','Intro','Verso','Pre-estribillo','Estribillo','Puente','Desarrollo','Repetición y contraste','Crear progresiones','Crear melodías sobre acordes','Cambio de tonalidad','Color modal'].map((n,i)=>entry(['composition-progression','composition-melody','harmonic-rhythm','form','intro','verse','prechorus','chorus','bridge','development','repetition-contrast','create-progressions','melody-over-chords','key-change','modal-color'][i],n,'composition',n==='Ritmo armónico'?'La velocidad con la que cambian los acordes; no es el patrón de batería.':`${n} es una herramienta estructural para convertir ideas musicales en una pieza coherente.`))
];
