import type {TheoryArticle} from '../types';
const t=(title:string,body:string)=>({type:'text' as const,title,body});
const f=(formula:string,caption?:string)=>({type:'formula' as const,formula,caption});
const e=(title:string,lines:string[],body?:string)=>({type:'example' as const,title,lines,body});
const c=(kind:'importance'|'try'|'warning',title:string,body:string)=>({type:'callout' as const,kind,title,body});
export const DEEP_ARTICLES:TheoryArticle[]=[
{id:'major-scale',title:'Escala mayor',aliases:['major scale','jónico','T T S T T T S'],keywords:['armonización','tonalidad'],category:'scales',level:'basic',summary:'La referencia central del sistema tonal: siete notas construidas con un patrón fijo de tonos y semitonos.',sections:[t('Qué es','Una escala de siete notas cuya distribución produce una tónica estable, tercera mayor y sensible.'),f('1 2 3 4 5 6 7','T · T · S · T · T · T · S'),{type:'scale',title:'Construcción parametrizable',root:'C',scaleKey:'major',harmonize:true},c('importance','¿Por qué importa?','Permite entender grados, acordes diatónicos, funciones y modos con un mismo mapa transportable.')],related:['degrees','major-harmonization','ionian','key'],actions:[{label:'Explorar la escala mayor',target:'explore',root:'C',scaleKey:'major'}],lessonId:'major-scale'},
{id:'natural-minor',title:'Escala menor natural',aliases:['menor','minor scale','eólico'],keywords:['b3','b6','b7'],category:'scales',level:'basic',summary:'Escala de siete notas con 3ª, 6ª y 7ª menores respecto de la mayor paralela.',sections:[f('1 2 b3 4 5 b6 b7'),{type:'scale',title:'Construcción',root:'A',scaleKey:'minor',compareWith:'major',harmonize:true},t('Por qué funciona','La b3 define el color menor; b6 y b7 reducen la atracción tonal que aparece al elevar la sensible.')],related:['harmonic-minor','melodic-minor','aeolian'],actions:[{label:'Explorar A menor',target:'explore',root:'A',scaleKey:'minor'}]},
{id:'harmonic-minor',title:'Menor armónica',aliases:['harmonic minor'],category:'scales',level:'intermediate',summary:'Menor natural con séptima elevada para crear sensible y una dominante mayor.',sections:[f('1 2 b3 4 5 b6 7'),{type:'scale',title:'Construcción',root:'A',scaleKey:'harmonic-minor'},t('Por qué funciona','Elevar G a G# en A menor fortalece E7 → Am, a costa de una segunda aumentada entre F y G#.')],related:['natural-minor','dominant-function']},
{id:'melodic-minor',title:'Menor melódica',aliases:['melodic minor'],category:'scales',level:'intermediate',summary:'Escala menor con sexta y séptima mayores; en jazz suele conservar la misma forma al descender.',sections:[f('1 2 b3 4 5 6 7'),{type:'scale',title:'Construcción',root:'A',scaleKey:'melodic-minor'},c('warning','Depende del lenguaje','En tradición clásica se suelen distinguir formas ascendente y descendente; en jazz se usa habitualmente esta forma en ambas direcciones.')],related:['natural-minor','harmonic-minor']},
{id:'minor-pentatonic',title:'Pentatónica menor',aliases:['minor pentatonic','penta menor','1 b3 4 5 b7','b7'],category:'scales',level:'basic',summary:'Escala de cinco notas muy usada en rock, blues y numerosos lenguajes melódicos.',sections:[f('1 b3 4 5 b7'),{type:'scale',title:'A menor vs mayor pentatónica',root:'A',scaleKey:'minor-pentatonic',compareWith:'major-pentatonic'},e('Mezcla blues sobre A7',['A7: A C# E G','Pentatónica menor: A C D E G','C ↔ C#'], 'La tensión entre la b3 expresiva y la 3ª mayor del acorde es parte central del lenguaje blues; no es un error que deba borrarse.')],related:['major-pentatonic','minor-blues','blue-note'],actions:[{label:'Explorar A pentatónica menor',target:'explore',root:'A',scaleKey:'minor-pentatonic'}]},
{id:'major-pentatonic',title:'Pentatónica mayor',aliases:['major pentatonic','1 2 3 5 6'],category:'scales',level:'basic',summary:'Escala mayor de cinco notas que omite 4 y 7.',sections:[f('1 2 3 5 6'),{type:'scale',title:'Comparación',root:'A',scaleKey:'major-pentatonic',compareWith:'minor-pentatonic'}],related:['minor-pentatonic','major-scale']},
{id:'minor-blues',title:'Escala blues',aliases:['blues menor','blues scale','b5','blue note'],category:'scales',level:'basic',summary:'Pentatónica menor con una b5 añadida como nota expresiva de tensión y paso.',sections:[f('1 b3 4 b5 5 b7'),{type:'scale',title:'A blues',root:'A',scaleKey:'minor-blues'},e('Movimiento típico',['D → Eb → E'],'La b5 no necesita reposar como nota estable: su fricción y su movimiento son parte del gesto.')],related:['blue-note','minor-pentatonic'],actions:[{label:'Explorar A blues',target:'explore',root:'A',scaleKey:'minor-blues'}]},
{id:'mixolydian',title:'Mixolidio',aliases:['mixolydian','modo mixolidio','b7','dominante'],keywords:['escala madre','centro tonal'],category:'modes',level:'intermediate',summary:'Modo mayor con séptima menor, estrechamente ligado al sonido de acordes dominantes.',sections:[f('1 2 3 4 5 6 b7'),{type:'scale',title:'G mayor vs G mixolidio',root:'G',scaleKey:'mixolydian',compareWith:'major',harmonize:true},e('Escala madre',['C mayor: C D E F G A B','G mixolidio: G A B C D E F'],'Compartir notas con C mayor no significa estar musicalmente en C: G debe sentirse como centro.'),t('Por qué funciona','La 3ª mayor conserva el carácter mayor; la b7 elimina la sensible y conecta con I7 y bVII.'),c('warning','Error común','Empezar C mayor desde G no produce automáticamente G mixolidio. El acompañamiento, los puntos de reposo y el fraseo deben afirmar G.'),c('try','Probalo','Tocá G mayor y después G mixolidio. Aislá el cambio F# → F y escuchá cómo cambia la gravedad.')],related:['major-scale','mode','dominant7','tonal-center','modal-progressions'],actions:[{label:'Explorar G mixolidio',target:'explore',root:'G',scaleKey:'mixolydian'}]},
{id:'diminished-triad',title:'Triada disminuida',aliases:['acorde disminuido','diminished','dim','1 b3 b5'],category:'chords',level:'basic',summary:'Triada formada por una tercera menor y una quinta disminuida.',sections:[f('1 b3 b5'),{type:'chord',title:'B disminuido',root:'B',quality:'diminished',compareWith:['major','minor']},e('Intervalos',['B → D = tercera menor','B → F = quinta disminuida']),c('importance','¿Por qué importa?','Su inestabilidad crea dirección y aparece naturalmente en el séptimo grado de la escala mayor.')],related:['triads','tritone','major-harmonization'],actions:[{label:'Abrir B° en Acordes',target:'chords',root:'B',chordQuality:'diminished'}],lessonId:'diminished'},
{id:'dominant7',title:'Dominante 7',aliases:['acorde dominante','dominant 7','7','b7','G7'],category:'chords',level:'intermediate',summary:'Acorde mayor con séptima menor; su tritono interno puede crear una resolución muy fuerte.',sections:[f('1 3 5 b7'),{type:'chord',title:'G7',root:'G',quality:'dominant7'},e('Resolución hacia C',['G7: G B D F','C: C E G','B → C','F → E'],'Las dos voces del tritono se mueven por semitono en direcciones contrarias.'),c('try','Probalo','Tocá G7 y detenete. Luego resolvé en C y escuchá el movimiento B→C y F→E.')],related:['tritone','dominant-function','voice-leading'],actions:[{label:'Abrir G7 en Acordes',target:'chords',root:'G',chordQuality:'dominant7'}]},
{id:'secondary-dominants',title:'Dominantes secundarios',aliases:['dominante secundario','secondary dominant','V/ii'],keywords:['C#','tonicización'],category:'advanced-harmony',level:'intermediate',summary:'Dominantes que apuntan temporalmente a un acorde diatónico distinto de la tónica.',sections:[e('En C mayor',['C → A7 → Dm → G7 → C','A7: A C# E G','A7 → Dm = V/ii','C → C#'],'C# no pertenece a C mayor, pero actúa como sensible de D y crea dirección hacia Dm.'),t('Por qué funciona','El acorde objetivo se oye momentáneamente como una pequeña tónica, sin que eso obligue a una modulación completa.'),c('warning','Contexto','Una dominante secundaria se identifica por su resolución y función, no sólo por tener una nota cromática.')],related:['tonicization','dominant7','voice-leading'],actions:[{label:'Abrir en Progresiones',target:'progressions'}]},
{id:'modal-interchange',title:'Intercambio modal',aliases:['acordes prestados','modal interchange','borrowed chords'],category:'advanced-harmony',level:'intermediate',summary:'Uso de acordes tomados de un modo paralelo para añadir color sin abandonar necesariamente la tónica.',sections:[e('Mayor con iv menor',['C → F → Fm → C','F: F A C','Fm: F Ab C','A → Ab → G'],'Fm puede entenderse como prestado de C menor; el descenso cromático conecta las voces con claridad.'),t('Por qué funciona','La tónica C se mantiene estable mientras cambia momentáneamente el vocabulario modal.')],related:['voice-leading','mode-vs-key','modulation'],actions:[{label:'Abrir en Progresiones',target:'progressions'}]},
{id:'chord-tones',title:'Chord tones',aliases:['notas del acorde','arpeggio tones','1 3 5 b7'],category:'improvisation',level:'basic',summary:'Son las notas que forman el acorde que está sonando en ese momento.',sections:[{type:'chord',title:'D7',root:'D',quality:'dominant7'},f('1 3 5 b7'),t('Cómo usarlo','Apuntar a chord tones en tiempos estructurales hace audible la armonía; las demás notas pueden conectar, ornamentar o tensar.')],related:['arpeggios','target-notes','guide-tones'],actions:[{label:'Practicar chord tones',target:'practice',root:'D',chordQuality:'dominant7'}]},
{id:'guide-tones',title:'Guide tones',aliases:['notas guía','guide tones','3 y 7','3ª 7ª'],category:'improvisation',level:'intermediate',summary:'La 3ª y la 7ª suelen revelar con economía la cualidad y el movimiento funcional de acordes de séptima.',sections:[e('ii–V–I en C',['Dm7: F · C','G7: B · F','Cmaj7: E · B'],'Observá notas comunes y movimientos cercanos: no hay una única conducción correcta.'),c('importance','¿Por qué importa?','Permiten escuchar los cambios aun sin tocar fundamentales y conectan improvisación, acompañamiento y voice leading.')],related:['voice-leading','chord-tones','two-five-one'],actions:[{label:'Practicar chord tones',target:'practice'}]},
{id:'voice-leading',title:'Voice leading',aliases:['conducción de voces','movimiento de voces'],category:'advanced-harmony',level:'intermediate',summary:'Estudia cómo se mueve cada voz de un acorde al siguiente.',sections:[e('G7 → Cmaj7',['G7: G B D F','Cmaj7: C E G B','B → C','F → E','G = nota común'],'La conducción suave aprovecha notas comunes y movimientos de semitono o tono. Los saltos no están prohibidos: son una decisión de textura.'),c('importance','¿Por qué importa?','Conecta acordes con fluidez al acompañar, arreglar e improvisar; no se reduce a usar inversiones.')],related:['guide-tones','inversions','modal-interchange','dominant7']},
{id:'arpeggios',title:'Arpegios',aliases:['arpeggio','notas del acorde'],category:'chords',level:'basic',summary:'Un arpegio recorre melódicamente las notas de un acorde en vez de hacerlas sonar simultáneamente.',sections:[e('Mismo material, distinto gesto',['Acorde: C + E + G simultáneamente','Arpegio: C → E → G']),t('Cómo usarlo','Los arpegios hacen visibles los cambios armónicos dentro de una línea y permiten practicar chord tones por todo el instrumento.')],related:['chord-tones','triads','seventh-chords'],actions:[{label:'Practicar arpegios',target:'practice'},{label:'Ver lección de arpegios',target:'learn',lessonId:'arpeggio-intro'}],lessonId:'arpeggio-intro'},
{id:'blue-note',title:'Blue note',aliases:['nota blues','b5'],category:'improvisation',level:'basic',summary:'Nota de inflexión expresiva cuya afinación, ataque y resolución pueden ser tan importantes como su nombre fijo.',sections:[f('b5','Dentro de la escala blues menor'),e('A blues',['A C D Eb E G','D → Eb → E'],'Eb crea fricción y movimiento entre 4 y 5; no es simplemente una nota “de otra escala”.')],related:['minor-blues','pentatonic-mix']},
{id:'harmonic-rhythm',title:'Ritmo armónico',aliases:['harmonic rhythm','velocidad de acordes'],category:'composition',level:'basic',summary:'La velocidad con la que cambian los acordes, no el patrón rítmico de la batería.',sections:[e('Mismos acordes, otro ritmo armónico',['| C | Am | F | G |','| C Am | F G |'],'En el segundo caso los cambios ocurren el doble de rápido y alteran la sensación de impulso.')],related:['progressions','form','tempo']}
];
