export type PanelHelp={theory:string;usage:string[];terms:{name:string;meaning:string}[]};
export const PANEL_HELP={
 configuration:{theory:'La tónica es el centro de reposo. La escala define qué intervalos se organizan alrededor de ese centro.',usage:['Elegí primero una tónica.','Seleccioná una escala o modo.','Los demás paneles se recalculan automáticamente.'],terms:[{name:'Tónica',meaning:'Nota que funciona como centro tonal.'},{name:'Escala',meaning:'Conjunto ordenado de notas.'},{name:'Modo',meaning:'Organización interválica con un centro y color propios.'}]},
 scale:{theory:'Una escala se describe por su fórmula de intervalos. Dos escalas pueden compartir notas pero percibirse distintas si cambia el centro tonal.',usage:['Leé las notas junto con sus grados.','Compará el rasgo característico con la escala mayor o menor de referencia.','Usá la escala mayor madre para entender los modos diatónicos.'],terms:[{name:'Grado',meaning:'Posición de una nota respecto de la tónica.'},{name:'Rasgo',meaning:'Intervalo que ayuda a reconocer el color de la escala.'},{name:'Escala madre',meaning:'Escala mayor que comparte las notas de un modo diatónico.'}]},
 fretboard:{theory:'Una misma altura aparece varias veces en la guitarra. El mástil permite relacionar el patrón físico con grados y funciones musicales.',usage:['Cambiá entre notas, grados o ambos.','Desplazá horizontalmente para llegar a los trastes superiores.','Seleccioná una posición para ver su intervalo.'],terms:[{name:'Traste',meaning:'División que eleva la nota un semitono.'},{name:'Afinación estándar',meaning:'E–A–D–G–B–E desde la sexta cuerda.'},{name:'Nota característica',meaning:'Grado modal destacado cuando realmente existe.'}]},
 harmony:{theory:'Armonizar una escala consiste en apilar terceras sobre cada grado. La calidad de cada acorde surge de las distancias entre sus notas.',usage:['Elegí tríadas o tétradas.','Seleccioná un acorde para inspeccionar notas e intervalos.','Usá los números romanos para transportar funciones a otra tonalidad.'],terms:[{name:'Tríada',meaning:'Acorde de tres notas construido normalmente con terceras.'},{name:'Tétrada',meaning:'Tríada con una séptima añadida.'},{name:'Número romano',meaning:'Función y calidad del acorde dentro de la escala.'}]},
 progressions:{theory:'Una progresión combina funciones armónicas en el tiempo. La sensación de dirección depende de tensión, resolución, ritmo y conducción de voces.',usage:['Agregá acordes diatónicos, prestados o dominantes secundarios.','Usá una progresión de estilo como punto de partida.','Reordená acordes y agregá cadencias sin borrar la secuencia.'],terms:[{name:'Intercambio modal',meaning:'Uso de acordes tomados de una tonalidad paralela.'},{name:'Dominante secundario',meaning:'Acorde V7 que dirige temporalmente hacia otro grado.'},{name:'Cadencia',meaning:'Fórmula armónica que produce cierre o suspensión.'},{name:'Conducción de voces',meaning:'Movimiento de cada nota entre acordes consecutivos.'}]},
 song:{theory:'La forma organiza el contraste y la repetición a gran escala. Una canción puede reutilizar armonía y modificar registro, dinámica o densidad entre secciones.',usage:['Elegí un tipo de sección y agregalo.','Definí compases, repeticiones, tonalidad y progresión.','Reordená o duplicá bloques para desarrollar la forma.'],terms:[{name:'Sección',meaning:'Bloque formal como verso, estribillo o puente.'},{name:'Compás',meaning:'Unidad métrica que organiza pulsos.'},{name:'Repetición',meaning:'Cantidad de veces consecutivas que suena una sección.'},{name:'Puente',meaning:'Sección contrastante que conecta o renueva la forma.'}]},
 chordScale:{theory:'La relación acorde–escala compara las notas estructurales del acorde con escalas que pueden acompañarlo. El contexto decide qué tensión resulta estable.',usage:['Seleccioná primero un acorde en Armonización.','Revisá qué escalas contienen todas sus notas.','Probá las tensiones disponibles y escuchá las notas marcadas como cautela.'],terms:[{name:'Chord tone',meaning:'Nota estructural que pertenece al acorde.'},{name:'Tensión',meaning:'Nota adicional que aporta color sin sustituir la estructura.'},{name:'Cautela',meaning:'Nota que puede generar fricción fuerte según voicing y contexto.'}]},
 modes:{theory:'El continuo modal ordena los siete modos desde el más brillante al más oscuro. Cada paso baja un único grado un semitono.',usage:['Compará las notas reales para una misma tónica.','Observá el grado que cambia entre modos vecinos.','Usá Jónico como referencia cuando la escala elegida no sea modal.'],terms:[{name:'Modo paralelo',meaning:'Modo que comparte la misma tónica con otro.'},{name:'Brillo modal',meaning:'Descripción relativa asociada a la cantidad de grados elevados o rebajados.'}]},
 voicings:{theory:'Un voicing es una disposición concreta de las notas de un acorde. La inversión depende de qué nota aparece en el bajo.',usage:['Elegí fundamental, calidad e inversión.','Compará posiciones en distintas zonas del mástil.','Buscá formas con movimientos pequeños respecto del acorde anterior.'],terms:[{name:'Voicing',meaning:'Distribución y duplicación concreta de las voces de un acorde.'},{name:'Inversión',meaning:'Estado definido por la nota del acorde ubicada en el bajo.'},{name:'Estado fundamental',meaning:'Voicing cuya nota más grave es la fundamental.'}]},
 detector:{theory:'Un conjunto de alturas puede formar un acorde exacto o estar contenido en varias escalas. La fundamental no siempre es deducible sin contexto.',usage:['Seleccioná notas sobre cualquier cuerda.','Lisa resaltará todas sus posiciones equivalentes.','Revisá acordes exactos y escalas posibles.'],terms:[{name:'Altura',meaning:'Identidad sonora de una nota sin considerar su octava.'},{name:'Coincidencia exacta',meaning:'La selección contiene exactamente las notas de la escala o acorde.'},{name:'Enarmonía',meaning:'Nombres distintos para una misma altura, como F♯ y G♭.'}]},
 tools:{theory:'Un intervalo describe la distancia entre dos notas. Su cantidad cromática se mide en semitonos, aunque el nombre exacto también depende del spelling.',usage:['Elegí una nota inicial y una final.','Leé la distancia cromática y las denominaciones posibles.','Recordá que seis semitonos pueden escribirse como cuarta aumentada o quinta disminuida.'],terms:[{name:'Semitono',meaning:'Distancia mínima del sistema cromático occidental.'},{name:'Intervalo',meaning:'Distancia y relación escrita entre dos notas.'},{name:'Tritono',meaning:'Distancia de seis semitonos: cuarta aumentada o quinta disminuida.'}]},
 circle:{theory:'El círculo ordena tonalidades por quintas. Al avanzar se agrega un sostenido; al retroceder se agrega un bemol.',usage:['Seleccioná una tonalidad en el círculo.','Consultá su armadura y relativa menor.','Compará tonalidades vecinas para modulaciones cercanas.'],terms:[{name:'Armadura',meaning:'Sostenidos o bemoles propios de una tonalidad.'},{name:'Relativa menor',meaning:'Tonalidad menor que comparte armadura con una mayor.'},{name:'Tonalidad vecina',meaning:'Tonalidad cercana en el círculo y con muchas notas comunes.'}]},
} satisfies Record<string,PanelHelp>;
