import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {getChordFromScale,type ChordRecord} from '../music/chords';
import {analyzeVoiceLeading,getBorrowedChords,getCadences,getSecondaryDominants} from '../music/composition';
import {ROOT_OPTIONS} from '../music/notes';
import {appendProgressionItems,formatProgression,moveProgressionItem,type ProgressionItem} from '../music/progressions';
import type {ScaleKey} from '../music/scales';
import {MUSICAL_STYLES,resolveStyleProgression,STYLE_PROGRESSIONS,type MusicalStyle,type ProgressionMode,type StyleProgression} from '../music/styleProgressions';
import {getProgressionVariations,type ProgressionVariation} from '../music/compositionVariations';
import type {Instrument} from '../music/instrument';
import {ProgressionChordMap} from './ProgressionChordMap';

export function ProgressionBuilder({root,scaleKey,instrument='guitar',onSelectChord,onProgressionChange}:{root:string;scaleKey:ScaleKey;instrument?:Instrument;onSelectChord?:(chord:ChordRecord)=>void;onProgressionChange?:(items:ProgressionItem[])=>void}){
 const[progressionRoot,setProgressionRoot]=useState(root),[tetrads,setTetrads]=useState(true),[items,setItems]=useState<ProgressionItem[]>([]),[style,setStyle]=useState<'all'|MusicalStyle>('all'),[modeFilter,setModeFilter]=useState<'all'|ProgressionMode>('all');const nextId=useRef(0);
 const onProgressionChangeRef=useRef(onProgressionChange);useEffect(()=>{onProgressionChangeRef.current=onProgressionChange},[onProgressionChange]);useEffect(()=>{onProgressionChangeRef.current?.(items)},[items]);
 useEffect(()=>{setProgressionRoot(root);setItems([])},[root,scaleKey]);
 const harmony=useMemo(()=>getChordFromScale(progressionRoot,scaleKey,tetrads),[progressionRoot,scaleKey,tetrads]);
 const borrowed=useMemo(()=>getBorrowedChords(progressionRoot,scaleKey),[progressionRoot,scaleKey]);
 const dominants=useMemo(()=>getSecondaryDominants(progressionRoot,scaleKey),[progressionRoot,scaleKey]);
 const cadences=useMemo(()=>getCadences(progressionRoot,scaleKey),[progressionRoot,scaleKey]);
 const voiceLeading=useMemo(()=>items.slice(0,-1).map((item,index)=>analyzeVoiceLeading(item.chord,items[index+1].chord)),[items]);
 const stylePresets=useMemo(()=>STYLE_PROGRESSIONS.filter(preset=>(style==='all'||preset.style===style)&&(modeFilter==='all'||preset.mode===modeFilter||preset.mode==='either')),[style,modeFilter]);
 const variations=useMemo(()=>getProgressionVariations(items.map(item=>item.chord),progressionRoot,scaleKey),[items,progressionRoot,scaleKey]);
 const formatted=formatProgression(items);
 function append(chord:ChordRecord,annotation?:string){onSelectChord?.(chord);setItems(current=>[...current,{id:`progression-${nextId.current++}`,chord,annotation}])}
 function appendCadence(chords:ChordRecord[],name:string){setItems(current=>appendProgressionItems(current,chords.map(chord=>({id:`progression-${nextId.current++}`,chord,annotation:name}))))}
 function appendStylePreset(preset:StyleProgression){const resolved=resolveStyleProgression(progressionRoot,preset);if(resolved)setItems(current=>appendProgressionItems(current,resolved.chords.map(chord=>({id:`progression-${nextId.current++}`,chord,annotation:`${preset.style} · ${preset.name}`}))))}
 function applyVariation(variation:ProgressionVariation){setItems(variation.chords.map(chord=>({id:`progression-${nextId.current++}`,chord,annotation:variation.name})))}
 return <div className="progression-builder">
  <div className="progression-controls"><label>Tonalidad<select value={progressionRoot} onChange={e=>{setProgressionRoot(e.target.value);setItems([])}}>{ROOT_OPTIONS.map(note=><option key={note}>{note}</option>)}</select></label><div className="segmented"><button aria-pressed={!tetrads} onClick={()=>{setTetrads(false);setItems([])}}>Tríadas</button><button aria-pressed={tetrads} onClick={()=>{setTetrads(true);setItems([])}}>Tétradas</button></div></div>
  <div className="style-library"><div className="style-library-head"><div><h3>Biblioteca por estilos</h3><p>Los acordes se transportan a la tonalidad elegida. El ritmo, tempo y voicing terminan de definir el estilo.</p></div><div><label>Estilo<select value={style} onChange={e=>setStyle(e.target.value as typeof style)}><option value="all">Todos</option>{MUSICAL_STYLES.map(item=><option key={item}>{item}</option>)}</select></label><label>Centro<select value={modeFilter} onChange={e=>setModeFilter(e.target.value as typeof modeFilter)}><option value="all">Mayor y menor</option><option value="major">Mayor</option><option value="minor">Menor</option></select></label></div></div><div className="style-preset-grid">{stylePresets.map(preset=>{const resolved=resolveStyleProgression(progressionRoot,preset);return <article key={preset.id}><header><span>{preset.style}</span><small>{preset.difficulty} · {preset.meter}</small></header><h4>{preset.name}</h4><strong>{preset.steps.map(step=>step.roman).join(' – ')}</strong><p>{resolved?.chords.map(chord=>chord.label).join(' – ')}</p><small>{preset.description}</small><button onClick={()=>appendStylePreset(preset)}>Agregar progresión</button></article>})}</div></div>
  <ComposerPalette title="Acordes diatónicos" description="Acordes propios de la escala seleccionada.">{harmony.map(chord=><PaletteButton key={chord.degreeName} chord={chord} detail={chord.degreeName} onClick={()=>append(chord,chord.degreeName)}/>)}</ComposerPalette>
  {borrowed.length>0&&<ComposerPalette title="Intercambio modal" description="Acordes prestados de la tonalidad paralela.">{borrowed.map(({chord,source})=><PaletteButton key={`${chord.label}-${chord.degreeName}`} chord={chord} detail={`${chord.degreeName} · de ${source}`} onClick={()=>append(chord,`Prestado de ${source}`)}/>)}</ComposerPalette>}
  {dominants.length>0&&<ComposerPalette title="Dominantes secundarios" description="Cada dominante resuelve por quinta hacia su acorde objetivo.">{dominants.map(({chord,target,functionLabel})=><PaletteButton key={`${chord.label}-${functionLabel}`} chord={chord} detail={`${functionLabel} → ${target.label}`} onClick={()=>append(chord,`${functionLabel} de ${target.label}`)}/>)}</ComposerPalette>}
  {cadences.length>0&&<div className="cadence-palette"><h3>Cadencias</h3><p>La cadencia se agrega al final de la progresión sin borrar lo que ya construiste.</p><div>{cadences.map(cadence=><button key={cadence.key} onClick={()=>appendCadence(cadence.chords,cadence.name)}><strong>{cadence.name}</strong><span>{cadence.chords.map(chord=>chord.label).join(' – ')}</span><small>{cadence.description}</small></button>)}</div></div>}
  {!harmony.length?<p className="empty-state">La escala seleccionada no tiene siete grados diatónicos para construir esta progresión.</p>:<><div className="progression-track">{items.map((item,index)=><div key={item.id}><strong>{item.chord.label}</strong><span>{item.chord.degreeName||item.annotation}</span><ProgressionChordMap chord={item.chord} instrument={instrument}/>{item.annotation&&item.annotation!==item.chord.degreeName&&<small>{item.annotation}</small>}<div><button aria-label={`Mover ${item.chord.label} a la izquierda`} disabled={index===0} onClick={()=>setItems(current=>moveProgressionItem(current,index,index-1))}>←</button><button aria-label={`Mover ${item.chord.label} a la derecha`} disabled={index===items.length-1} onClick={()=>setItems(current=>moveProgressionItem(current,index,index+1))}>→</button><button aria-label={`Quitar ${item.chord.label}`} onClick={()=>setItems(current=>current.filter(({id})=>id!==item.id))}>×</button></div></div>)}</div>{items.length?<><div className="progression-result"><p><strong>Acordes:</strong> {formatted.chords}</p><p><strong>Grados:</strong> {formatted.romans}</p><button onClick={()=>setItems([])}>Limpiar progresión</button></div>{variations.length>0&&<div className="variation-lab"><h3>Variaciones inteligentes</h3><p>Cada propuesta muestra qué cambia. Aplicarla reemplaza la secuencia actual por esa variante.</p><div>{variations.map(variation=><article key={variation.key}><h4>{variation.name}</h4><strong>{variation.chords.map(chord=>chord.label).join(' – ')}</strong><p>{variation.description}</p><small>{variation.change}</small><button onClick={()=>applyVariation(variation)}>Aplicar variación</button></article>)}</div></div>}{voiceLeading.length>0&&<div className="voice-leading"><h3>Conducción de voces</h3>{voiceLeading.map((analysis,index)=><article key={`${analysis.from}-${analysis.to}-${index}`}><header><strong>{analysis.from} → {analysis.to}</strong><span>{analysis.summary}</span></header>{analysis.commonTones.length>0&&<p>Notas comunes: {analysis.commonTones.join(', ')}</p>}<div>{analysis.movements.map((move,i)=><span key={`${move.from}-${move.to}-${i}`} className={move.semitones===0?'common':''}>{move.from} → {move.to} · {move.direction}{move.semitones!==0?` ${Math.abs(move.semitones)} st`:''}</span>)}</div></article>)}</div>}</>:<p className="empty-state">Agregá acordes o aplicá una cadencia para comenzar.</p>}</>}
 </div>
}

function ComposerPalette({title,description,children}:{title:string;description:string;children:ReactNode}){return <div className="composer-palette"><h3>{title}</h3><p>{description}</p><div>{children}</div></div>}
function PaletteButton({chord,detail,onClick}:{chord:ChordRecord;detail:string;onClick:()=>void}){return <button onClick={onClick}><strong>{chord.label}</strong><span>{detail}</span><small>Agregar</small></button>}
