import {useMemo,useState} from 'react';
import {ALL_CHORD_TYPES,buildChord,getChordTypeByKey,isChordQuality,type ChordQuality} from '../music/chords';
import {ROOT_OPTIONS} from '../music/notes';
import {buildVoicings,type ChordInversion,type GuitarVoicing} from '../music/voicings';

const INVERSION_LABELS:Record<ChordInversion,string>={root:'Estado fundamental',first:'Primera inversión',second:'Segunda inversión',third:'Tercera inversión',extension:'Extensión en el bajo'};
function VoicingDiagram({voicing}:{voicing:GuitarVoicing}){const start=voicing.minFret===0?0:Math.max(1,voicing.minFret);const frets=Array.from({length:5},(_,i)=>start+i);return <article className="voicing-card"><header><strong>{INVERSION_LABELS[voicing.inversion]}</strong><span>Bajo: {voicing.bassNote}</span></header><div className="voicing-diagram"><div className="voicing-fret-labels"><span/>{frets.map(f=><span key={f}>{f}</span>)}</div>{[5,4,3,2,1,0].map(stringIndex=><div className="voicing-string" key={stringIndex}><b>{['E','A','D','G','B','E'][stringIndex]}</b>{frets.map(fret=>{const position=voicing.positions.find(p=>p.stringIndex===stringIndex&&p.fret===fret);return <span key={fret} className={position?`tone tone-${position.chordTone}`:''}>{position?.noteName??''}</span>})}</div>)}</div></article>}

export function Voicings(){
 const[root,setRoot]=useState('C'),[quality,setQuality]=useState<ChordQuality>('major'),[inversion,setInversion]=useState<'all'|ChordInversion>('all');
 const all=useMemo(()=>buildVoicings(root,quality),[root,quality]),chord=useMemo(()=>buildChord(root,quality),[root,quality]),definition=getChordTypeByKey(quality);
 const voicings=inversion==='all'?all:all.filter(v=>v.inversion===inversion),extended=Boolean(definition.voicingFormula);
 const prioritizedDegrees=definition.voicingFormula?.map(interval=>definition.degreeLabels?.[definition.formula.indexOf(interval)]).filter((degree):degree is string=>Boolean(degree));
 const omittedDegrees=definition.degreeLabels?.filter(degree=>!prioritizedDegrees?.includes(degree))??[];
 return <div className="voicings"><div className="voicing-controls"><label>Fundamental<select value={root} onChange={e=>setRoot(e.target.value)}>{ROOT_OPTIONS.map(n=><option key={n}>{n}</option>)}</select></label><label>Acorde<select value={quality} onChange={e=>{if(isChordQuality(e.target.value))setQuality(e.target.value)}}>{ALL_CHORD_TYPES.map(type=><option value={type.key} key={type.key}>{type.label}</option>)}</select></label><label>Inversión<select value={inversion} onChange={e=>setInversion(e.target.value as typeof inversion)}><option value="all">Todas</option><option value="root">Estado fundamental</option><option value="first">Primera</option><option value="second">Segunda</option><option value="third">Tercera</option><option value="extension">Extensión en el bajo</option></select></label></div>
 {chord&&<div className="voicing-spelling"><div><span>Acorde</span><strong>{chord.label}</strong></div><div><span>Spelling completo</span><strong>{chord.notes.join(' ')}</strong></div><div><span>Fórmula</span><strong>{chord.degrees.join(' · ')}</strong></div>{extended&&<div><span>Voces priorizadas</span><strong>{prioritizedDegrees?.join(' · ')}</strong></div>}{omittedDegrees.length>0&&<div><span>Omisión posible</span><strong>{omittedDegrees.join(' · ')}</strong></div>}</div>}
 {extended&&<p className="notice">Los acordes extendidos completos aparecen arriba. En el mástil se omiten únicamente las voces indicadas para adaptarlos a seis cuerdas.</p>}<p className="voicing-count">{voicings.length} posiciones encontradas hasta el traste 15. Cada forma contiene las voces priorizadas y ocupa como máximo cinco trastes.</p><div className="voicing-grid">{voicings.map(voicing=><VoicingDiagram key={voicing.id} voicing={voicing}/>)}</div>{!voicings.length&&<p className="empty-state">No hay posiciones para este filtro.</p>}</div>
}
