import {useCallback,useEffect,useMemo,useState} from 'react';
import {ALL_CHORD_TYPES,buildChord,type ChordQuality,type ChordRecord} from '../music/chords';
import {ROOT_OPTIONS} from '../music/notes';
import type {ProgressionItem} from '../music/progressions';
import {FRET_ZONES,PRACTICE_APPROACHES,PRACTICE_GENRES,analyzePracticeNote,explainPracticeNote,getTargetNotes,parseChordLabel,scaleLabel,suggestScales,type CountInBars,type PracticeApproach,type PracticeChordConfig,type PracticeGenre,type PracticeMode,type PracticeScale,type PracticeSession} from '../music/practiceSuggestions';
import {loadPracticeSession,saveNamedPractice,savePracticeSession} from '../music/practicePersistence';
import {PracticeFretboard} from '../components/PracticeFretboard';
import {ArrowLeft,ArrowRight,Copy,Trash2} from 'lucide-react';
import {Focus,Pause,Play,RotateCcw} from 'lucide-react';
import {usePracticePlayback} from '../hooks/usePracticePlayback';
import {resolveChordBars,type PlaybackConfig} from '../music/practicePlayback';
import {findClosestVoiceMovements,getArpeggio,type ArpeggioExtent} from '../music/arpeggios';

const makeId=()=>`practice-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const makeConfig=(chord:ChordRecord,index=0):PracticeChordConfig=>({id:makeId(),chord,scale:null,zoneId:FRET_ZONES[index%FRET_ZONES.length].id,source:'suggested'});
const makeSession=(items:readonly ProgressionItem[],approach:PracticeApproach='global'):PracticeSession=>({mode:'guided',genre:'unspecified',approach,activeChordIndex:0,keepNearby:true,target:'both',globalScale:null,chordConfigs:(items.length?items:[{id:'a',chord:buildChord('A','dominant7')!}]).map((x,i)=>makeConfig(x.chord,i)),bpm:80,beatsPerBar:4,globalBars:1,loop:true,countIn:0,showNextTarget:true,arpeggioExtent:'full',showGuideTones:true,labelMode:'notes'});

type Props={incomingProgression:ProgressionItem[];incomingChord:ChordRecord|null;incomingScale:PracticeScale|null;incomingApproach:PracticeApproach|null;onConsume:()=>void};
export function PracticeSection({incomingProgression,incomingChord,incomingScale,incomingApproach,onConsume}:Props){
 const[session,setSession]=useState<PracticeSession>(()=>loadPracticeSession()??makeSession(incomingProgression));
 const[entry,setEntry]=useState(''),[saveName,setSaveName]=useState(''),[focus,setFocus]=useState(false);
 useEffect(()=>{if(incomingProgression.length)setSession(makeSession(incomingProgression,incomingApproach??'global'));else if(incomingChord)setSession(makeSession([{id:makeId(),chord:incomingChord}],incomingApproach??'global'));else if(incomingScale)setSession(s=>({...s,approach:'global',globalScale:incomingScale,chordConfigs:s.chordConfigs.map(c=>({...c,scale:incomingScale}))}));if(incomingProgression.length||incomingChord||incomingScale)onConsume()},[incomingProgression,incomingChord,incomingScale,incomingApproach,onConsume]);
 useEffect(()=>savePracticeSession(session),[session]);
 const chords=session.chordConfigs.map(c=>c.chord),active=session.chordConfigs[session.activeChordIndex];
 const suggestions=useMemo(()=>active?suggestScales(active.chord,chords,session.genre,session.approach):[],[active,chords,session.genre,session.approach]);
 const shownScale:PracticeScale=active?.scale??session.globalScale??suggestions[0]??{root:'A',scaleKey:'minor-blues'};
 const targets=active?getTargetNotes(active.chord,session.target):[];
 const update=(patch:Partial<PracticeSession>)=>setSession(s=>({...s,...patch}));
 const onPlaybackChord=useCallback((index:number)=>setSession(s=>{const previous=s.chordConfigs[s.activeChordIndex],chordConfigs=s.keepNearby&&previous?s.chordConfigs.map((config,i)=>i===index?{...config,zoneId:previous.zoneId}:config):s.chordConfigs;return{...s,chordConfigs,activeChordIndex:index}}),[]);
 const playbackConfig=useMemo<PlaybackConfig>(()=>({bpm:session.bpm,beatsPerBar:session.beatsPerBar,globalBars:session.globalBars,chordBars:session.chordConfigs.map(c=>c.bars),loop:session.loop,countInBars:session.countIn}),[session.bpm,session.beatsPerBar,session.globalBars,session.chordConfigs,session.loop,session.countIn]);
 const playback=usePracticePlayback(playbackConfig,onPlaybackChord),next=playback.position.nextChordIndex===null?null:session.chordConfigs[playback.position.nextChordIndex],nextTargets=next?getTargetNotes(next.chord,'both'):[];
 const activeExtent=active?.arpeggioExtent??session.arpeggioExtent,activeArpeggio=active?getArpeggio(active.chord,activeExtent):null,nextArpeggio=next?getArpeggio(next.chord,next.arpeggioExtent??session.arpeggioExtent):null,connection=activeArpeggio&&nextArpeggio?findClosestVoiceMovements(activeArpeggio,nextArpeggio):null,isArpeggioMode=session.approach==='arpeggios'||session.approach==='mixed';
 function updateConfig(index:number,fn:(value:PracticeChordConfig)=>PracticeChordConfig){setSession(s=>({...s,chordConfigs:s.chordConfigs.map((c,i)=>i===index?fn(c):c)}))}
 function chooseScale(scale:PracticeScale,index=session.activeChordIndex){setSession(s=>{const global=s.approach==='global'||s.approach==='mixed';return{...s,globalScale:global?scale:s.globalScale,chordConfigs:s.chordConfigs.map((c,i)=>global?(c.source==='manual'&&i!==index?c:{...c,scale,source:i===index?'manual':c.source}):i===index?{...c,scale,source:'manual'}:c)}})}
 function setApproach(approach:PracticeApproach){setSession(s=>({...s,approach,chordConfigs:s.chordConfigs.map(c=>c.source==='manual'?c:{...c,scale:suggestScales(c.chord,s.chordConfigs.map(x=>x.chord),s.genre,approach)[0]??c.scale})}))}
 function add(){const chord=parseChordLabel(entry);if(chord){setSession(s=>({...s,chordConfigs:[...s.chordConfigs,makeConfig(chord,s.chordConfigs.length)]}));setEntry('')}}
 function move(index:number,delta:number){setSession(s=>{const next=[...s.chordConfigs],to=index+delta;if(to<0||to>=next.length)return s;[next[index],next[to]]=[next[to],next[index]];return{...s,chordConfigs:next,activeChordIndex:to}})}
 function selectChord(index:number){update({activeChordIndex:index});if(playback.playing)playback.jump(index)}
 return <div className={`section-view practice-section ${focus?'focus-mode':''}`}>
  <section className="card practice-player"><div className="player-now"><small>{playback.position.phase==='count-in'?'Preparado…':'Ahora'}</small><strong>{playback.position.phase==='count-in'?playback.position.beat:active?.chord.label}</strong><span>{playback.position.phase==='count-in'?`Count-in · ${playback.position.countInBeat}`:isArpeggioMode?`Arpegio · ${activeArpeggio?.notes.join(' · ')}`:`${scaleLabel(shownScale)} · Posición ${FRET_ZONES.find(z=>z.id===active?.zoneId)?.position??1}`}</span></div><div className="player-next"><small>Siguiente</small><strong>{next?.chord.label??'Fin'}</strong><span>{session.showNextTarget&&nextArpeggio&&isArpeggioMode?`Arpegio: ${nextArpeggio.notes.join(' · ')}`:playback.position.phase==='playing'?`Compás ${playback.position.bar}/${resolveChordBars(playbackConfig,playback.position.chordIndex)} · Pulso ${playback.position.beat}/${session.beatsPerBar}`:'Listo para comenzar'}</span></div><div className="player-actions"><button aria-label={playback.playing?'Pausar':'Reproducir'} onClick={playback.playing?playback.pause:playback.play}>{playback.playing?<Pause/>:<Play/>}</button><button aria-label="Detener y reiniciar" onClick={playback.stop}><RotateCcw/></button><button aria-label="Modo Focus" aria-pressed={focus} onClick={()=>setFocus(v=>!v)}><Focus/></button></div><div className="playback-progress"><i style={{width:`${playback.position.progress*100}%`}}/></div></section>
  <section className="card playback-settings secondary-config"><label>BPM<input type="number" min="30" max="240" value={session.bpm} onChange={e=>update({bpm:Math.min(240,Math.max(30,Number(e.target.value)))})}/></label><label>Compás<select value={session.beatsPerBar} onChange={e=>update({beatsPerBar:Number(e.target.value) as 3|4|6})}><option value="4">4/4</option><option value="3">3/4</option><option value="6">6/8</option></select></label><label>Duración<select value={session.globalBars} onChange={e=>update({globalBars:Number(e.target.value)})}><option value="1">1 compás</option><option value="2">2 compases</option><option value="4">4 compases</option></select></label><label>Count-in<select value={session.countIn} onChange={e=>update({countIn:Number(e.target.value) as CountInBars})}><option value="0">Off</option><option value="1">1 compás</option><option value="2">2 compases</option></select></label><label className="toggle"><input type="checkbox" checked={session.loop} onChange={e=>update({loop:e.target.checked})}/> Loop</label><label className="toggle"><input type="checkbox" checked={session.showNextTarget} onChange={e=>update({showNextTarget:e.target.checked})}/> Próximo objetivo</label></section>
  <section className="card practice-controls secondary-config">
   <div className="segmented">{([['free','Libre'],['guided','Guiado'],['challenge','Desafío']] as [PracticeMode,string][]).map(([v,l])=><button key={v} aria-pressed={session.mode===v} onClick={()=>update({mode:v})}>{l}</button>)}</div>
   {session.mode==='challenge'&&<p className="practice-challenge">Consigna: usá una sola idea durante la progresión y marcá cada cambio con la 3ª o la 7ª.</p>}
   <div className="controls"><label>Género / estilo<select value={session.genre} onChange={e=>update({genre:e.target.value as PracticeGenre})}>{PRACTICE_GENRES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><small>Preset de sugerencias, no una regla.</small></label><label>Enfoque<select value={session.approach} onChange={e=>setApproach(e.target.value as PracticeApproach)}>{PRACTICE_APPROACHES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><small aria-hidden="true">&nbsp;</small></label>{isArpeggioMode&&<><label>Arpegio<select value={session.arpeggioExtent} onChange={e=>update({arpeggioExtent:e.target.value as ArpeggioExtent})}><option value="triad">Triada</option><option value="seventh">Séptima</option><option value="full">Completo</option></select></label><label>Etiquetas<select value={session.labelMode} onChange={e=>update({labelMode:e.target.value as 'notes'|'degrees'})}><option value="notes">Notas</option><option value="degrees">Grados</option></select></label><label className="toggle"><input type="checkbox" checked={session.showGuideTones} onChange={e=>update({showGuideTones:e.target.checked})}/> Destacar guide tones</label></>}</div>
  </section>
  <section className="card secondary-config"><div className="section-head"><div><h2>Progresión</h2><p>Ingresá A7, Dm7, Cmaj7 u otro símbolo.</p></div><div className="practice-add"><input value={entry} onChange={e=>setEntry(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="A7"/><button onClick={add}>Agregar acorde</button></div></div><div className="practice-progression">{session.chordConfigs.map((c,i)=><button key={c.id} aria-pressed={i===session.activeChordIndex} onClick={()=>selectChord(i)}>{c.chord.label}</button>)}</div></section>
  <section className="card practice-config secondary-config"><h2>Configuración por acorde</h2><div className="practice-table">{session.chordConfigs.map((c,i)=><article key={c.id} className={i===session.activeChordIndex?'active':''}>
   <header className="practice-card-head"><button className="practice-chord-name" onClick={()=>update({activeChordIndex:i})}>{c.chord.label}<small>{i===session.activeChordIndex?'Acorde actual':'Seleccionar'}</small></button><div className="row-actions">
    <button aria-label={`Mover ${c.chord.label} a la izquierda`} title="Mover a la izquierda" disabled={!i} onClick={()=>move(i,-1)}><ArrowLeft aria-hidden="true"/></button>
    <button aria-label={`Mover ${c.chord.label} a la derecha`} title="Mover a la derecha" disabled={i===session.chordConfigs.length-1} onClick={()=>move(i,1)}><ArrowRight aria-hidden="true"/></button>
    <button aria-label={`Duplicar ${c.chord.label}`} title="Duplicar" onClick={()=>setSession(s=>({...s,chordConfigs:[...s.chordConfigs.slice(0,i+1),{...c,id:makeId()},...s.chordConfigs.slice(i+1)]}))}><Copy aria-hidden="true"/></button>
    <button className="danger" aria-label={`Eliminar ${c.chord.label}`} title="Eliminar" onClick={()=>setSession(s=>({...s,activeChordIndex:Math.max(0,s.activeChordIndex-1),chordConfigs:s.chordConfigs.filter(x=>x.id!==c.id)}))}><Trash2 aria-hidden="true"/></button>
   </div></header>
   <label>Fundamental<select value={c.chord.root} onChange={e=>updateConfig(i,x=>({...x,chord:buildChord(e.target.value,x.chord.quality)!}))}>{ROOT_OPTIONS.map(n=><option key={n}>{n}</option>)}</select></label>
   <label>Calidad<select value={c.chord.quality} onChange={e=>updateConfig(i,x=>({...x,chord:buildChord(x.chord.root,e.target.value as ChordQuality)!}))}>{ALL_CHORD_TYPES.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label>
   <label>Escala elegida<select value={c.scale?`${c.scale.root}|${c.scale.scaleKey}`:''} onChange={e=>{const[root,scaleKey]=e.target.value.split('|');update({activeChordIndex:i});chooseScale({root,scaleKey:scaleKey as PracticeScale['scaleKey']},i)}}><option value="">Sin elegir</option>{suggestScales(c.chord,chords,session.genre,session.approach).map(s=><option key={`${s.root}-${s.scaleKey}`} value={`${s.root}|${s.scaleKey}`}>{s.label}</option>)}</select><small>{c.source==='manual'?'Selección manual':'Sugerencia editable'}</small></label>
   <label>Posición / zona<select value={c.zoneId} onChange={e=>updateConfig(i,x=>({...x,zoneId:e.target.value}))}>{FRET_ZONES.map(z=><option key={z.id} value={z.id}>Posición {z.position} · {z.label}</option>)}</select></label>{isArpeggioMode&&<label>Arpegio del acorde<select value={c.arpeggioExtent??''} onChange={e=>updateConfig(i,x=>({...x,arpeggioExtent:e.target.value?e.target.value as ArpeggioExtent:undefined}))}><option value="">Global</option><option value="triad">Triada</option><option value="seventh">Séptima</option><option value="full">Completo</option></select></label>}<label>Compases<select value={c.bars??''} onChange={e=>updateConfig(i,x=>({...x,bars:e.target.value?Number(e.target.value):undefined}))}><option value="">Global ({session.globalBars})</option><option value="1">1</option><option value="2">2</option><option value="4">4</option></select></label>
  </article>)}</div></section>
  {active&&<><section className="card"><div className="section-head"><div><h2>Mástil · {session.approach==='arpeggios'?`Arpegio de ${active.chord.label}`:scaleLabel(shownScale)}</h2><p>{isArpeggioMode?`${activeArpeggio?.notes.join(' · ')} · ${activeArpeggio?.degrees.join(' · ')}`:`${active.chord.label} activo; los objetivos tienen prioridad visual.`}</p></div><label className="keep-zone"><input type="checkbox" checked={session.keepNearby} onChange={e=>update({keepNearby:e.target.checked})}/> Mantenerme en esta zona</label></div><PracticeFretboard scale={shownScale} chord={active.chord} zoneId={active.zoneId} target={session.target} approach={session.approach} arpeggioExtent={activeExtent} showGuideTones={session.showGuideTones} labelMode={session.labelMode}/></section>
   <div className="practice-lower"><section className="card"><h2>Qué practicar ahora</h2><label>Notas objetivo<select value={session.target} onChange={e=>update({target:e.target.value as PracticeSession['target']})}><option value="third">3ª</option><option value="seventh">7ª</option><option value="both">3ª y 7ª</option><option value="all">Todas las chord tones</option></select></label><p><b>Acorde:</b> {active.chord.label}<br/><b>{isArpeggioMode?'Arpegio':'Escala'}:</b> {isArpeggioMode?activeArpeggio?.notes.join(' · '):scaleLabel(shownScale)}</p>{isArpeggioMode&&<p className="practice-challenge">Improvisá usando sólo las notas de {active.chord.label}. Intentá resolver en {getTargetNotes(active.chord,'both').join(' o ')}. La 3ª y la 7ª suelen definir gran parte del carácter y la función del acorde.</p>}<div className="target-explanations">{targets.map(note=>{const analysis=analyzePracticeNote({note,baseScale:shownScale,chord:active.chord});return <article key={note}><strong>{note}</strong><span>{analysis.chordRelation.degree==='1'?'Fundamental':analysis.chordRelation.description} de {active.chord.label}</span><p>{explainPracticeNote(analysis,shownScale,active.chord)}</p></article>})}</div>{connection&&next&&<aside className="next-targets"><small>Conectar con {next.chord.label}</small><strong>Notas comunes: {connection.commonNotes.join(' · ')||'—'}</strong>{connection.movements.slice(0,3).map(move=><span key={`${move.from}-${move.to}`}>{move.from} → {move.to} · {move.semitones} semitono{move.semitones===2?'s':''}</span>)}</aside>}{session.showNextTarget&&playback.position.beat===session.beatsPerBar&&next&&<aside className="next-targets"><small>Próximo: {next.chord.label}</small><strong>{isArpeggioMode?`Arpegio: ${nextArpeggio?.notes.join(' · ')}`:`Objetivos: ${nextTargets.join(' · ')}`}</strong></aside>}</section>
  <section className="card"><h2>Sugerir escalas</h2><p>Opciones ordenadas, no respuestas absolutas.</p><div className="suggestion-list">{suggestions.map(s=><button key={`${s.root}-${s.scaleKey}`} onClick={()=>chooseScale(s)}><strong>{s.label}</strong><span>{s.compatibility}</span><small>{s.explanation}</small></button>)}</div></section></div></>}
  <section className="card practice-save"><h2>Guardar práctica</h2><input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder="Blues A - penta global"/><button disabled={!saveName.trim()} onClick={()=>{saveNamedPractice(session,saveName.trim());setSaveName('')}}>Guardar práctica</button><small>La última sesión se recupera automáticamente; se conservan hasta 12 prácticas.</small></section>
 </div>
}



