import {useEffect,useMemo,useState} from 'react';
import {Search,ChevronLeft,ExternalLink} from 'lucide-react';
import {buildChord,getScaleNotes,harmonizeScale,type ChordQuality,type ScaleKey} from '../music/theory';
import {THEORY_ARTICLES,THEORY_CATEGORIES,getTheoryArticle,searchTheory} from '../theory/content';
import type {TheoryAction,TheoryArticle,TheoryCategory,TheorySection as Block} from '../theory/types';

const ROOTS=['C','C#','Db','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const levelLabel={basic:'Fundamental',intermediate:'Intermedio',advanced:'Avanzado'} as const;
function setHash(id?:string){history.replaceState(null,'',id?`#theory/${id}`:'#theory')}
function Formula({value}:{value:string}){return <div className="theory-formula">{value.split(' ').map((x,i)=><strong key={`${x}-${i}`}>{x.replace(/b/g,'♭').replace(/#/g,'♯')}</strong>)}</div>}
function ScaleBlock({block}:{block:Extract<Block,{type:'scale'}>}){const[root,setRoot]=useState(block.root),notes=getScaleNotes(root,block.scaleKey),other=block.compareWith?getScaleNotes(root,block.compareWith):null,chords=block.harmonize?harmonizeScale(root,block.scaleKey):[];return <section className="theory-block"><div className="theory-block-head"><h2>{block.title}</h2><label>Tónica<select value={root} onChange={e=>setRoot(e.target.value)}>{ROOTS.map(n=><option key={n}>{n}</option>)}</select></label></div><div className="theory-note-row">{notes.map((n,i)=><span key={n} className={other&&other[i]!==n?'changed':''}><b>{n}</b><small>{i+1}</small></span>)}</div>{other&&<><p className="comparison-label">Comparación</p><div className="theory-note-row muted">{other.map((n,i)=><span key={`${n}-${i}`} className={notes[i]!==n?'changed':''}><b>{n}</b><small>{i+1}</small></span>)}</div></>}{chords.length>0&&<div className="theory-harmony"><h3>Armonización</h3>{chords.map(ch=><span key={ch.degreeName}><b>{ch.label}</b><small>{ch.degreeName}</small></span>)}</div>}</section>}
function ChordBlock({block}:{block:Extract<Block,{type:'chord'}>}){const main=buildChord(block.root,block.quality),comparisons=block.compareWith?.map(q=>buildChord(block.root,q)).filter(Boolean)??[];return <section className="theory-block"><h2>{block.title}</h2>{main&&<div className="chord-example"><strong>{main.label}</strong><Formula value={main.degrees.join(' ')}/><span>{main.notes.join(' · ')}</span></div>}{comparisons.map(ch=><div className="comparison-chord" key={ch!.label}><b>{ch!.label}</b><span>{ch!.notes.join(' · ')}</span></div>)}</section>}
function RenderBlock({block}:{block:Block}){if(block.type==='scale')return <ScaleBlock block={block}/>;if(block.type==='chord')return <ChordBlock block={block}/>;if(block.type==='formula')return <section className="theory-block"><h2>{block.title??'Fórmula'}</h2><Formula value={block.formula}/>{block.caption&&<p>{block.caption}</p>}</section>;if(block.type==='example')return <section className="theory-block"><h2>{block.title}</h2><div className="theory-example">{block.lines.map((l,i)=><code key={i}>{l}</code>)}</div>{block.body&&<p>{block.body}</p>}</section>;if(block.type==='comparison')return <section className="theory-block"><h2>{block.title}</h2>{block.items.map(x=><div key={x.label}><b>{x.label}</b>{x.formula&&<Formula value={x.formula}/>}<p>{x.notes?.join(' · ')}</p></div>)}</section>;if(block.type==='callout')return <aside className={`theory-callout ${block.kind}`}><strong>{block.title}</strong><p>{block.body}</p></aside>;return <section className="theory-block"><h2>{block.title}</h2><p>{block.body}</p></section>}
export function TheorySection({onExplore,onChord,onProgressions,onPractice,onLearn}:{onExplore:(r:string,s:ScaleKey)=>void;onChord:(r:string,q:ChordQuality)=>void;onProgressions:()=>void;onPractice:(r?:string,q?:ChordQuality)=>void;onLearn:(lesson?:string)=>void}){const initial=location.hash.startsWith('#theory/')?location.hash.slice(8):null,[articleId,setArticleId]=useState(initial),[query,setQuery]=useState(''),[category,setCategory]=useState<TheoryCategory|null>(null),article=getTheoryArticle(articleId??'');const results=useMemo(()=>query.trim()?searchTheory(query):category?THEORY_ARTICLES.filter(a=>a.category===category):[],[query,category]);useEffect(()=>{const handler=()=>setArticleId(location.hash.startsWith('#theory/')?location.hash.slice(8):null);addEventListener('hashchange',handler);return()=>removeEventListener('hashchange',handler)},[]);function open(id:string){setArticleId(id);setHash(id);scrollTo({top:0,behavior:'smooth'})}function action(a:TheoryAction){if(a.target==='explore')onExplore(a.root??'C',a.scaleKey??'major');else if(a.target==='chords')onChord(a.root??'C',a.chordQuality??'major');else if(a.target==='progressions')onProgressions();else if(a.target==='practice')onPractice(a.root,a.chordQuality);else onLearn(a.lessonId)}
 if(article)return <div className="theory-layout"><aside className="theory-index"><strong>Índice</strong>{THEORY_CATEGORIES.map(cat=><button key={cat.id} onClick={()=>{setCategory(cat.id);setArticleId(null);setHash()}}>{cat.label}</button>)}</aside><article className="theory-article"><button className="back-button" onClick={()=>{setArticleId(null);setHash()}}><ChevronLeft/> Teoría</button><nav className="breadcrumb">Teoría › {THEORY_CATEGORIES.find(c=>c.id===article.category)?.label} › {article.title}</nav><header><span className={`level ${article.level}`}>{levelLabel[article.level]}</span><h1>{article.title}</h1><p>{article.summary}</p></header>{article.sections.map((b,i)=><RenderBlock key={i} block={b}/>)}{(article.actions?.length||article.lessonId)&&<section className="theory-actions"><h2>Llevalo a Lisa</h2>{article.actions?.map(a=><button key={a.label} onClick={()=>action(a)}>{a.label}<ExternalLink/></button>)}{article.lessonId&&!article.actions?.some(a=>a.target==='learn')&&<button onClick={()=>onLearn(article.lessonId)}>Aprender paso a paso<ExternalLink/></button>}</section>}{article.related?.length&&<section className="related"><h2>Relacionado</h2>{article.related.map(getTheoryArticle).filter(Boolean).map(a=><button key={a!.id} onClick={()=>open(a!.id)}>{a!.title}</button>)}</section>}</article></div>;
 return <div className="theory-home"><header><p className="eyebrow">Biblioteca</p><h1>Teoría musical</h1><p>Buscá un concepto o explorá por tema. Desde cada explicación podés saltar a las herramientas de Lisa.</p><label className="theory-search"><Search/><input autoFocus={false} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar teoría..."/></label></header>{query.trim()||category?<section><div className="results-head"><h2>{query?`Resultados para “${query}”`:THEORY_CATEGORIES.find(c=>c.id===category)?.label}</h2>{category&&<button onClick={()=>setCategory(null)}>Ver todas</button>}</div><div className="article-grid">{results.map(a=><ArticleCard key={a.id} article={a} onOpen={open}/>)}{!results.length&&<p>No encontramos ese término. Probá un alias, fórmula o concepto relacionado.</p>}</div></section>:<><section><h2>Explorá por tema</h2><div className="category-grid">{THEORY_CATEGORIES.map(cat=>{const count=THEORY_ARTICLES.filter(a=>a.category===cat.id).length;return <button key={cat.id} onClick={()=>setCategory(cat.id)}><strong>{cat.label}</strong><span>{cat.description}</span><small>{count} artículos</small></button>})}</div></section><section><h2>Conceptos fundamentales</h2><div className="article-grid">{['interval','major-scale','triads','harmonic-function','chord-tones','voice-leading'].map(getTheoryArticle).filter(Boolean).map(a=><ArticleCard key={a!.id} article={a!} onOpen={open}/>)}</div></section></>}</div>}
function ArticleCard({article,onOpen}:{article:TheoryArticle;onOpen:(id:string)=>void}){return <button className="article-card" onClick={()=>onOpen(article.id)}><span>{THEORY_CATEGORIES.find(c=>c.id===article.category)?.label} · {levelLabel[article.level]}</span><strong>{article.title}</strong><p>{article.summary}</p></button>}
