import {useEffect,useMemo,useState} from 'react';
import {ALL_SCALES,getChordFromScale,getScaleByKey,ROOT_OPTIONS,type ScaleKey} from './music/theory';
import {Navigation,type Section} from './components/layout/Navigation';import {ScaleSummary} from './components/explorer/ScaleSummary';import {Fretboard} from './components/Fretboard';import {HarmonyTable} from './components/HarmonyTable';import {ModeComparer} from './components/ModeComparer';import {IntervalTool} from './components/IntervalTool';import {ChordTool} from './components/ChordTool';import {CircleOfFifths} from './components/CircleOfFifths';

export default function App(){const[root,setRoot]=useState('G'),[scaleKey,setScaleKey]=useState<ScaleKey>('mixolydian'),[tetrads,setTetrads]=useState(false),[labels,setLabels]=useState<'notes'|'degrees'|'both'>('both'),[selected,setSelected]=useState(''),[active,setActive]=useState<Section>('explorar'),[menu,setMenu]=useState(false);const scale=getScaleByKey(scaleKey),harmony=useMemo(()=>getChordFromScale(root,scaleKey,tetrads),[root,scaleKey,tetrads]);useEffect(()=>{if(!harmony.some(c=>c.label===selected))setSelected(harmony[0]?.label??'')},[harmony,selected]);const chord=harmony.find(c=>c.label===selected);
return <div className="app"><Navigation open={menu} setOpen={setMenu} active={active} setActive={setActive}/><main><div className="shell"><header className="page-header"><div><p className="eyebrow">Explorador musical</p><h1>Entendé la escala, no sólo la forma.</h1></div></header>
<section className="card controls" id="explorar"><label>Tónica<select value={root} onChange={e=>setRoot(e.target.value)}>{ROOT_OPTIONS.map(n=><option key={n}>{n}</option>)}</select></label><label>Escala / modo<select value={scaleKey} onChange={e=>setScaleKey(e.target.value as ScaleKey)}>{ALL_SCALES.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label></section>
<ScaleSummary root={root} scaleKey={scaleKey}/>
<section className="card fret-card"><div className="section-head"><div><h2>Mástil de guitarra</h2><p>Afinación estándar · 22 trastes; desplazá horizontalmente.</p></div><div className="segmented" role="group" aria-label="Etiquetas del mástil">{(['notes','degrees','both'] as const).map(v=><button key={v} type="button" aria-pressed={labels===v} onClick={()=>setLabels(v)}>{v==='notes'?'Notas':v==='degrees'?'Grados':'Ambos'}</button>)}</div></div><Fretboard root={root} scaleKey={scaleKey} labelMode={labels}/><div className="legend"><span><i className="root"/>Tónica</span>{scale.characteristicDegree&&<span><i className="characteristic"/>Rasgo {scale.characteristicDegree}</span>}<span><i className="scale"/>Escala</span><span><i/>Fuera de escala</span></div></section>
<section className="card" id="armonia"><div className="section-head"><div><h2>Armonización</h2><p>Acordes construidos por terceras dentro de la escala.</p></div><div className="segmented"><button aria-pressed={!tetrads} onClick={()=>setTetrads(false)}>Tríadas</button><button aria-pressed={tetrads} onClick={()=>setTetrads(true)}>Tétradas</button></div></div><HarmonyTable harmony={harmony} selectedChordLabel={selected} onSelectChord={setSelected}/>{chord&&<div className="chord-detail"><strong>{chord.label} · {chord.degreeName}</strong><span>Notas: {chord.notes.join(' ')}</span><span>Fórmula: {chord.degrees.join(' ')}</span><span>Intervalos: {chord.intervals.join(' · ')}</span></div>}</section>
<section className="card" id="modos"><div className="section-head"><div><h2>Continuo modal</h2><p>Cada paso altera un único grado descendiendo un semitono.</p></div></div><ModeComparer root={root} currentKey={scaleKey}/></section>
<section className="card tools-grid" id="herramientas"><div><h2>Intervalos</h2><p>Cálculo cromático en semitonos.</p><IntervalTool/></div><div><h2>Acordes</h2><p>Spelling por función de cada voz.</p><ChordTool/></div></section>
<section className="card" id="circulo"><div className="section-head"><div><h2>Círculo de quintas</h2><p>Armaduras y relativas menores.</p></div></div><CircleOfFifths currentRoot={root} onSelect={setRoot}/></section><footer>Lisa · teoría musical para guitarra</footer></div></main></div>}
