import {useEffect,useMemo,useState} from 'react';
import {SELECTABLE_SCALES,getChordFromScale,getScaleByKey,ROOT_OPTIONS,type ScaleKey} from './music/theory';
import {Navigation,type Section} from './components/layout/Navigation';import {CollapsiblePanel} from './components/layout/CollapsiblePanel';import {ScaleSummary} from './components/explorer/ScaleSummary';import {Fretboard} from './components/Fretboard';import {HarmonyTable} from './components/HarmonyTable';import {ModeComparer} from './components/ModeComparer';import {IntervalTool} from './components/IntervalTool';import {CircleOfFifths} from './components/CircleOfFifths';import {Voicings} from './components/Voicings';import {ProgressionBuilder} from './components/ProgressionBuilder';import {ChordScaleAnalysis} from './components/ChordScaleAnalysis';import {ReverseFretboard} from './components/ReverseFretboard';
import {PANEL_HELP} from './content/panelHelp';
import {SongStructure} from './components/SongStructure';

export default function App(){const[root,setRoot]=useState('G'),[scaleKey,setScaleKey]=useState<ScaleKey>('mixolydian'),[tetrads,setTetrads]=useState(false),[labels,setLabels]=useState<'notes'|'degrees'|'both'>('both'),[selected,setSelected]=useState(''),[active,setActive]=useState<Section>('explorar'),[menu,setMenu]=useState(false);const scale=getScaleByKey(scaleKey),harmony=useMemo(()=>getChordFromScale(root,scaleKey,tetrads),[root,scaleKey,tetrads]);useEffect(()=>{if(!harmony.some(c=>c.label===selected))setSelected(harmony[0]?.label??'')},[harmony,selected]);const chord=harmony.find(c=>c.label===selected);
return <div className="app"><Navigation open={menu} setOpen={setMenu} active={active} setActive={setActive}/><main><div className="shell"><header className="page-header"><div><p className="eyebrow">Explorador musical</p><h1>Entendé la escala, no sólo la forma.</h1></div></header>
<CollapsiblePanel help={PANEL_HELP.configuration} id="explorar" title="Configuración" description="Elegí la tónica y la escala que querés explorar."><div className="controls"><label>Tónica<select value={root} onChange={e=>setRoot(e.target.value)}>{ROOT_OPTIONS.map(n=><option key={n}>{n}</option>)}</select></label><label>Escala / modo<select value={scaleKey} onChange={e=>setScaleKey(e.target.value as ScaleKey)}>{SELECTABLE_SCALES.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label></div></CollapsiblePanel>
<ScaleSummary root={root} scaleKey={scaleKey}/>
<CollapsiblePanel help={PANEL_HELP.fretboard} title="Mástil de guitarra" description="Afinación estándar · 22 trastes; desplazá horizontalmente." className="fret-card"><div className="panel-toolbar"><div className="segmented" role="group" aria-label="Etiquetas del mástil">{(['notes','degrees','both'] as const).map(v=><button key={v} type="button" aria-pressed={labels===v} onClick={()=>setLabels(v)}>{v==='notes'?'Notas':v==='degrees'?'Grados':'Ambos'}</button>)}</div></div><Fretboard root={root} scaleKey={scaleKey} labelMode={labels}/><div className="legend"><span><i className="root"/>Tónica</span>{scale.characteristicDegree&&<span><i className="characteristic"/>Rasgo {scale.characteristicDegree}</span>}<span><i className="scale"/>Escala</span><span><i/>Fuera de escala</span></div></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.harmony} id="armonia" title="Armonización" description="Acordes construidos por terceras dentro de la escala."><div className="panel-toolbar"><div className="segmented"><button aria-pressed={!tetrads} onClick={()=>setTetrads(false)}>Tríadas</button><button aria-pressed={tetrads} onClick={()=>setTetrads(true)}>Tétradas</button></div></div><HarmonyTable harmony={harmony} selectedChordLabel={selected} onSelectChord={setSelected}/>{chord&&<div className="chord-detail"><strong>{chord.label} · {chord.degreeName}</strong><span>Notas: {chord.notes.join(' ')}</span><span>Fórmula: {chord.degrees.join(' ')}</span><span>Intervalos: {chord.intervals.join(' · ')}</span></div>}</CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.progressions} id="progresiones" title="Progresiones armónicas" description="Construí, ordená y transportá progresiones con los acordes de la escala."><ProgressionBuilder root={root} scaleKey={scaleKey}/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.song} id="cancion" title="Estructura de canción" description="Organizá secciones, compases, repeticiones y progresiones."><SongStructure defaultRoot={root}/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.chordScale} id="acorde-escala" title="Relación acorde–escala" description="Escalas compatibles, tensiones disponibles y notas de cautela."><ChordScaleAnalysis chord={chord??null}/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.modes} id="modos" title="Continuo modal" description="Cada paso altera un único grado descendiendo un semitono."><ModeComparer root={root} currentKey={scaleKey}/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.voicings} id="voicings" title="Voicings" description="Inversiones y disposiciones tocables del acorde sobre el mástil."><Voicings/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.detector} id="detector" title="Detector desde el mástil" description="Seleccioná notas para identificar acordes y escalas posibles."><ReverseFretboard/></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.tools} id="herramientas" title="Intervalos" description="Calculadora cromática y referencia de distancias."><div className="interval-panel"><p>Compará dos notas para conocer su distancia en semitonos y su nombre interválico.</p><IntervalTool/></div></CollapsiblePanel>
<CollapsiblePanel help={PANEL_HELP.circle} id="circulo" title="Círculo de quintas" description="Armaduras y relativas menores."><CircleOfFifths currentRoot={root} onSelect={setRoot}/></CollapsiblePanel><footer>Lisa · teoría musical para guitarra</footer></div></main></div>}
